Public Class PA_Accounting_AdjustingDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property ORG_CODE As String
    Public Property PERIOD_ID As Decimal?
    Public Property PERIOD_NAME As String
    Public Property ORG_SET_ID As Decimal?
    Public Property ORG_SET_NAME As String
    Public Property ADJUSTING_X As Decimal?
    Public Property ADJUSTING_DATE As Date?
    Public Property FROM_DATE As Date?
    Public Property TO_DATE As Date?
    Public Property YEAR As Decimal?
    Public Property NOTE As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property IS_TER As Boolean?
End Class
