Public Class PA_Delegacy_TaxDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property ORG_CODE As String
    Public Property EMP_STATUS As Decimal?
    Public Property EMP_STATUS_NAME As String
    Public Property YEAR As Decimal?
    Public Property JOIN_DATE As Date?
    Public Property DELEGACY As Boolean?
    Public Property IS_TER As Boolean?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property PIT_CODE As String
    Public Property FROM_DATE As Date?
    Public Property TO_DATE As Date?
    Public Property BIRTH_DATE As Date?
    Public Property GENDER As String
    Public Property MOBILE_PHONE As String
    Public Property EMAIL As String
End Class
