Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteToDataSet
Datetime: 08/29/2022 8:30:07 AM
Error message: ORA-04063: package body "BCG_LIVE.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_LIVE.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 105
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteToDataSet
Datetime: 08/29/2022 8:30:07 AM
Error message: ORA-04063: package body "BCG_LIVE.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_LIVE.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 126
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 53
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteToDataSet
Datetime: 08/29/2022 8:32:25 AM
Error message: ORA-04063: package body "BCG_LIVE.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_LIVE.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 105
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteToDataSet
Datetime: 08/29/2022 8:32:25 AM
Error message: ORA-04063: package body "BCG_LIVE.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_LIVE.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 126
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 53
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteToDataSet
Datetime: 08/29/2022 8:34:32 AM
Error message: ORA-06502: PL/SQL: numeric or value error: character to number conversion error
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 105
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteToDataSet
Datetime: 08/29/2022 8:34:32 AM
Error message: ORA-06502: PL/SQL: numeric or value error: character to number conversion error
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteDataset(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 375
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 126
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 53
Other Text: PKG_PROFILE.SPS_INS_LIST_INSURANCE 
{
False,
}

________________________________________________________________________________________________________

