Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 07/13/2022 4:08:19 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/13/2022 4:08:19 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 07/13/2022 4:10:07 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/13/2022 4:10:07 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 07/13/2022 4:10:29 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/13/2022 4:10:29 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.AUTOCREATE_COMMENDNO 
{
1,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 07/13/2022 4:37:40 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.AUTOCREATE_DECISIONNO2 
{
1,
7067,
6681,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/13/2022 4:37:40 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.AUTOCREATE_DECISIONNO2 
{
1,
7067,
6681,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteStoreScalar
Datetime: 07/13/2022 4:41:50 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 144
Other Text: PKG_PROFILE.AUTOCREATE_DECISIONNO2 
{
1,
7067,
6645,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/13/2022 4:41:50 PM
Error message: ORA-04063: package body "BCG_DEV.PKG_PROFILE" has errors
ORA-06508: PL/SQL: could not find program unit being called: "BCG_DEV.PKG_PROFILE"
ORA-06512: at line 1
Stack trace:    at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, CommandType CommandType, String CommandText, OracleParameter[] CommandParameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 644
   at Histaff.DataAccessLayer.OracleHelper.ExecuteScalar(String ConnectionString, String StoredProceduredName, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 664
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 165
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 89
Other Text: PKG_PROFILE.AUTOCREATE_DECISIONNO2 
{
1,
7067,
6645,
07/13/2022 12:00:00 AM,
OUT_STRING,
}

________________________________________________________________________________________________________

