Function: Histaff.DataAccessLayer.DataAccess.QueryData.DataAccess => ExecuteToDataSet
Datetime: 07/12/2022 10:52:04 AM
Error message: OracleCommand.CommandText is invalid
Stack trace:    at Histaff.DataAccessLayer.OracleHelperParameterCache.DiscoverSpParameterSet(String ConnectionString, String StoredProceduredName, Boolean IncludeReturnValueParameter, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 849
   at Histaff.DataAccessLayer.OracleHelperParameterCache.GetSpParameterSet(String ConnectionString, String StoredProceduredName, Boolean IncludeReturnValueParameter) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 917
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 86
Other Text: PKG_PROFILE.GET_INFO_SALARYITEMSPERCENT2 
{
23,
07/12/2022 12:00:00 AM,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteToDataSet
Datetime: 07/12/2022 10:52:04 AM
Error message: OracleCommand.CommandText is invalid
Stack trace:    at Histaff.DataAccessLayer.OracleHelperParameterCache.DiscoverSpParameterSet(String ConnectionString, String StoredProceduredName, Boolean IncludeReturnValueParameter, Object[] ParameterValues) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 849
   at Histaff.DataAccessLayer.OracleHelperParameterCache.GetSpParameterSet(String ConnectionString, String StoredProceduredName, Boolean IncludeReturnValueParameter) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\OracleHelper.vb:line 917
   at Histaff.DataAccessLayer.DataAccess.QueryData.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\Histaff.DataAccessLayer\DataAccess.vb:line 126
   at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteToDataSet(String storeName, List`1 parameterValue) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 53
Other Text: PKG_PROFILE.GET_INFO_SALARYITEMSPERCENT2 
{
23,
07/12/2022 12:00:00 AM,
}

________________________________________________________________________________________________________

