Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/08/2022 1:04:53 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1231,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/08/2022 1:29:04 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1232,
}

________________________________________________________________________________________________________

