Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 9:55:49 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1210,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 9:57:56 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1211,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:12:22 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1212,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:18:45 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1213,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:26:11 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1214,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:35:37 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1215,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:40:40 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1216,
}

________________________________________________________________________________________________________

Function: HistaffFramework.ServiceImplementations.HistaffFramework.HistaffFramework => ExecuteStoreScalar
Datetime: 07/07/2022 10:52:26 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at HistaffFramework.ServiceImplementations.HistaffFramework.ExecuteStoreScalar(String storeName, List`1 parameters) in D:\GIT\BCG_DEV_NEW\HistaffFramework\HistaffFramework.OracleDataAccess.vb:line 92
Other Text: PKG_COMMON_LIST.UPDATE_AUTHOR_USER 
{
1217,
}

________________________________________________________________________________________________________

