Public Class PRO_TRAIN_OUT_COMPANY_DTO
    Public Property ID As Decimal
    Public Property YEAR_GRA As Decimal?
    Public Property NAME_SHOOLS As String
    Public Property FORM_TRAIN_ID As Decimal?
    Public Property FORM_TRAIN_NAME As String
    Public Property SPECIALIZED_TRAIN As String
    Public Property RESULT_TRAIN As String
    Public Property CERTIFICATE As Decimal?
    Public Property CERTIFICATE_CODE As String
    Public Property CERTIFICATE_NAME As String
    Public Property EFFECTIVE_DATE_FROM As Date?
    Public Property EFFECTIVE_DATE_TO As Date?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property FROM_DATE As Date?
    Public Property TO_DATE As Date?
    Public Property CREATED_DATE As Date?
    Public Property UPLOAD_FILE As String
    Public Property FILE_NAME As String
    Public Property TYPE_TRAIN_ID As Decimal?
    Public Property TYPE_TRAIN_NAME As String
    Public Property RECEIVE_DEGREE_DATE As Date?
    Public Property IS_RENEWED As Decimal?
    Public Property LEVEL_ID As Decimal?
    Public Property POINT_LEVEL As String
    Public Property CONTENT_LEVEL As String
    Public Property NOTE As String
    Public Property TRAIN_PLACE As Decimal?
    Public Property TRAIN_PLACE_NAME As String
    Public Property IS_MAIN As Decimal?
    Public Property TR_PROGRAM_RESULT_ID As Decimal?
End Class
