'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlMngInfoEvalTargetNewEdit

    '''<summary>
    '''ctrlMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlMessageBox As Global.Common.ctrlMessageBox

    '''<summary>
    '''Hid_IsEnter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Hid_IsEnter As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hidGoalID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidGoalID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''RadSplitter3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter3 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane1 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tbarOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbarOT As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''valSum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSum As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rtEmployee_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtEmployee_Code As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtEmployee_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtEmployee_id As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''reEMPLOYEE_CODE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reEMPLOYEE_CODE As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rnID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnID As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rtEmployee_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtEmployee_Name As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''btnFindEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFindEmployee As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''rtTitle_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtTitle_Name As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtTitle_Id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtTitle_Id As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtOrg_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtOrg_Name As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rtOrg_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rtOrg_id As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboStatus As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RequiredFieldValidator1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredFieldValidator1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cboYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboYear As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboPeriod As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''reqPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqPeriod As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rdStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdStartDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdEndDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''chkPortalShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPortalShow As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rdEffectDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdEffectDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''reqEffectDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqEffectDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtMonthNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthNumber As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoal As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''reqGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reqGoal As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''chkIsConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsConfirm As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCriteria As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtCriteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCriteria As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboUnit As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboFrequency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFrequency As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''cboSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSource As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboCriteriaType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCriteriaType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''cboEvaluateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboEvaluateType As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''txtTargets control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTargets As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtThreshold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtThreshold As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''rnWeighted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnWeighted As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''RadPane2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane2 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''rgData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgData As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadWindowManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadWindowManager1 As Global.Telerik.Web.UI.RadWindowManager

    '''<summary>
    '''rwPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwPopup As Global.Telerik.Web.UI.RadWindow

    '''<summary>
    '''phFindEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phFindEmp As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
