Function: SendMail
Datetime: 09/06/2022 9:00:17 AM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 9:01:17 AM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 9:06:09 AM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 9:11:16 AM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:41:51 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:44:51 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:49:51 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:51:28 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:51:53 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:51:54 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:52:51 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 1:55:51 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: CheckAndSendEventMail
Datetime: 09/06/2022 2:06:36 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.EntityClient.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.CheckAndSendEventMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1600
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:06:36 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:11:03 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:11:44 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:14:42 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at Oracle.DataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.EntityClient.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:15:39 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:15:40 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:16:47 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:16:50 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:16:52 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:17:38 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:17:39 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:24:44 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:29:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:30:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:32:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:37:42 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:40:42 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:42:42 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:43:42 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 2:44:42 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:00:54 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:02:54 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:07:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:10:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:15:54 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:17:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:24:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:25:55 PM
Error message: A recipient must be specified.
Stack trace:    at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1118
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:29:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:31:55 PM
Error message: A recipient must be specified.
Stack trace:    at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1118
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:35:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:45:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:51:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 3:57:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMailNoti
Datetime: 09/06/2022 4:06:55 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMailNoti(Decimal eventId) in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1643
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 4:23:03 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: CheckAndSendEventMail
Datetime: 09/06/2022 4:23:03 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at CommonDAL.CommonRepository.SendMailNoti(Decimal eventId) in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1699
   at CommonDAL.CommonRepository.CheckAndSendEventMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1614
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:49 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:51 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:51 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:52 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:53 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:53 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:54 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:55 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:09:56 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:57 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:57 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:58 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:58 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:58 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:58 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:10:59 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1114
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:13:49 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:15:49 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 09/06/2022 5:17:49 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

