Function: SendMail
Datetime: 08/24/2022 1:31:38 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1113
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 1:31:38 PM
Error message: Could not find a part of the path 'D:\Working\BCG\BCG_DEV\HistaffServiceHost\Profile\UploadFile\PortalEvent\483c02c2-7bc3-4681-bad5-c7b37dd81b79\179-11_wf.PNG'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1135
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 1:31:38 PM
Error message: Could not find a part of the path 'D:\Working\BCG\BCG_DEV\HistaffServiceHost\Profile\UploadFile\PortalEvent\483c02c2-7bc3-4681-bad5-c7b37dd81b79\015. Quyet dinh dieu chinh cap bac cong viec.doc'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1135
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:09:15 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:10:13 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:15:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:16:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:19:50 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:25:07 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

Function: SendMail
Datetime: 08/24/2022 5:36:27 PM
Error message: Execution of the command requires an open and available connection. The connection's current state is broken.
Stack trace:    at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CommonDAL.CommonRepository.SendMail() in D:\GIT\BCG_DEV_NEW\CommonDAL\CommonRepository.vb:line 1037
Other Text: iCommon

