Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:22:41 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:25:03 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:26:12 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:26:34 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:31:29 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:35:08 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:37:16 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

Function: CHECK_INS_ORG
Datetime: 07/04/2022 11:40:04 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at InsuranceDAL.InsuranceRepository.CHECK_INS_ORG(Decimal P_EMP_ID, Decimal P_INS_ORG_ID, DateTime P_ARISING_FROM_MONTH, String& pDate) in D:\GIT\BCG_DEV_NEW\InsuranceDAL\InsuranceRepository.Business.vb:line 3399
Other Text: iInsurance

