Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:35 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:35 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:42 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:28:42 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:29:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:29:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:29:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:29:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:33:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:33:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:33:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:33:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:34:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:34:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:34:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:34:47 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:35:05 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:35:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:35:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 11:35:07 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:32:15 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:32:16 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:35:24 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:35:26 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:35:32 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:35:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:35:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:50:14 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:50:15 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:50:15 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:50:15 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:51:27 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:51:27 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:51:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:51:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 1:52:05 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:17:55 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:17:56 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:17:58 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:02 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:09 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:13 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:17 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:33 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:18:47 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:19:20 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:19:22 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:19:23 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:19:24 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:22:50 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:22:51 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:00 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:08 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:13 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:14 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:35 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:36 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:23:38 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:31 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:32 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:41 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:52 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:53 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:24:55 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:25:12 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:25:26 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:25:27 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:25:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:25:52 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:26:42 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:26:43 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:26:45 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:27:52 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:30:01 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:30:09 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:30:10 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:30:13 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:30:29 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:34:40 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 4:34:42 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:01:09 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:10:51 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:10:52 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:10:58 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:10:59 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:11:02 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/30/2022 5:11:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

