Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:28 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:33 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:02:35 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:13 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:14 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:26 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:31 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:44 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:45 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:50:47 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:40 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:52:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:52 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:53 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:55:53 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:05 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:05 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:05 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:40 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:46 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:56:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:57:12 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:57:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:57:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:00 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:00 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:01 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:01 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:03 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:29 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 9:59:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:07 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:08 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:09 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:40 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:01:58 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:02:00 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:02:01 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:02:02 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:02:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:02:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:05:03 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:05:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:03 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:16 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:16 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:16 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:17 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:17 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:17 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:34 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:36 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:36 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:07:36 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:20 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:08:25 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:01 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:02 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:03 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:06 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:14 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:18 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:27 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:37 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:49 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:54 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:09:59 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:01 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:08 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:12 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:14 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:16 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:26 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:27 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:36 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:10:55 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:19 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:26 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:11:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:12:00 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:12:37 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:13:02 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:13:32 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:14:11 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:14:35 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:15:39 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:28 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:29 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:35 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:37 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:44 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:49 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:56 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:58 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:18:59 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:20 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:30 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:32 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:33 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:36 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:40 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:40 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:42 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:44 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:19:50 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:02 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:02 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:03 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:04 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:07 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:09 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:10 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:14 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:14 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:15 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:21 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:22 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:23 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:24 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:26 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:38 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:41 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:43 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:43 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:44 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:44 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 08/19/2022 10:20:47 AM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8667
Other Text: iTime

