Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:01 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:02 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:12 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:13 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:14 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:44:14 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:46:18 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:46:19 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:46:19 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/12/2022 4:46:20 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

