Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:38 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:41 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:43 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:51 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 2:59:53 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 3:00:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 3:02:07 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 3:02:09 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:00 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:01 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:03 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:07 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:08 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:10 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:29 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:31 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:10:32 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:11:05 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:11:06 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:11:12 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:11:21 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:36 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:38 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:40 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:41 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:43 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:50 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:55 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:56 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:13:56 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:31 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:32 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:34 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:36 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:39 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:15:44 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:26 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:27 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:28 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:30 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:32 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:33 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

Function: GetPortalOtRegData
Datetime: 09/06/2022 5:17:37 PM
Error message: ORA-00604: error occurred at recursive SQL level 1
ORA-01003: no statement parsed
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at AttendanceDAL.AttendanceRepository.GetPortalOtRegData(AT_OT_REGISTRATIONDTO _filter, Int32& Total, Int32 PageIndex, Int32 PageSize, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\AttendanceDAL\AttendanceRepository.Business.vb:line 8668
Other Text: iTime

