-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 4/28/2023 4:03:46 PM
-- Generated from EDMX file: E:\Source\BCG_DEV\InsuranceDAL\InsuranceContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR(4000) NULL,
   "FIRST_NAME_VN" NVARCHAR(4000) NULL,
   "LAST_NAME_VN" NVARCHAR(4000) NULL,
   "FULLNAME_VN" NVARCHAR(4000) NULL,
   "FIRST_NAME_EN" VARCHAR(8000) NULL,
   "LAST_NAME_EN" NVARCHAR(4000) NULL,
   "FULLNAME_EN" NVARCHAR(4000) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "WORK_STATUS" DECIMAL(18,0) NULL,
   "CONTRACT_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "JOIN_DATE" DATETIME NULL,
   "DIRECT_MANAGER" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "LAST_WORKING_ID" DECIMAL(18,0) NULL,
   "TER_EFFECT_DATE" DATETIME NULL,
   "TER_LAST_DATE" DATETIME NULL,
   "ITIME_ID" DECIMAL(18,0) NULL,
   "STAFF_RANK_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HU_EMPLOYEE_EDUCATION'
CREATE TABLE "dbo"."HU_EMPLOYEE_EDUCATION" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "ACADEMY" DECIMAL(18,0) NULL,
   "MAJOR" DECIMAL(18,0) NULL,
   "COMPUTER_CER1" NVARCHAR(4000) NULL,
   "COMPUTER_CER2" NVARCHAR(4000) NULL,
   "COMPUTER_CER3" NVARCHAR(4000) NULL,
   "COMPUTER_LEVEL1" DECIMAL(18,0) NULL,
   "COMPUTER_LEVEL2" DECIMAL(18,0) NULL,
   "COMPUTER_LEVEL3" DECIMAL(18,0) NULL,
   "COMPUTER_MARK1" NVARCHAR(4000) NULL,
   "COMPUTER_MARK2" NVARCHAR(4000) NULL,
   "COMPUTER_MARK3" NVARCHAR(4000) NULL,
   "LANGUAGE1" DECIMAL(18,0) NULL,
   "LANGUAGE2" DECIMAL(18,0) NULL,
   "LANGUAGE3" DECIMAL(18,0) NULL,
   "LANGUAGE_LEVEL1" DECIMAL(18,0) NULL,
   "LANGUAGE_LEVEL2" DECIMAL(18,0) NULL,
   "LANGUAGE_LEVEL3" DECIMAL(18,0) NULL,
   "LANGUAGE_MARK1" NVARCHAR(4000) NULL,
   "LANGUAGE_MARK2" NVARCHAR(4000) NULL,
   "LANGUAGE_MARK3" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "GRADUATE_SCHOOL" NVARCHAR(4000) NULL,
   "MARK_EDU" DECIMAL(18,0) NULL,
   "TRAINING_FORM" DECIMAL(18,0) NULL,
   "LEARNING_LEVEL" DECIMAL(18,0) NULL
);

-- Creating table 'HU_EMPLOYEE_FILES'
CREATE TABLE "dbo"."HU_EMPLOYEE_FILES" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "FILE_TYPE" DECIMAL(18,0) NULL,
   "FILE_NAME" NVARCHAR(4000) NULL,
   "FILE_SIZE" INT NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "UPLOAD_BY" NVARCHAR(4000) NULL,
   "UPLOAD_DATE" DATETIME NULL
);

-- Creating table 'HU_EMPLOYEE_HEALTH'
CREATE TABLE "dbo"."HU_EMPLOYEE_HEALTH" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "CHIEU_CAO" FLOAT NULL,
   "CAN_NANG" FLOAT NULL,
   "NHOM_MAU" NVARCHAR(4000) NULL,
   "HUYET_AP" NVARCHAR(4000) NULL,
   "MAT_TRAI" NVARCHAR(4000) NULL,
   "MAT_PHAI" NVARCHAR(4000) NULL,
   "TAI_MUI_HONG" NVARCHAR(4000) NULL,
   "RANG_HAM_MAT" NVARCHAR(4000) NULL,
   "TIM" NVARCHAR(4000) NULL,
   "PHOI_NGUC" NVARCHAR(4000) NULL,
   "VIEM_GAN_B" NVARCHAR(4000) NULL,
   "DA_HOA_LIEU" NVARCHAR(4000) NULL,
   "GHI_CHU_SUC_KHOE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "LOAI_SUC_KHOE" DECIMAL(18,0) NULL,
   "DU_SUC_KHOE" SMALLINT NULL
);

-- Creating table 'HU_EMPLOYEE_OTHER_INFO'
CREATE TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "NGAY_VAO_DOAN" DATETIME NULL,
   "NOI_VAO_DOAN" NVARCHAR(4000) NULL,
   "NOI_SINH_HOAT_DOAN" NVARCHAR(4000) NULL,
   "DOAN_PHI" SMALLINT NULL,
   "NGAY_VAO_DANG" DATETIME NULL,
   "NOI_VAO_DANG" NVARCHAR(4000) NULL,
   "NOI_SINH_HOAT_DANG" NVARCHAR(4000) NULL,
   "DANG_PHI" SMALLINT NULL,
   "SO_TAI_KHOAN" NVARCHAR(4000) NULL,
   "NGAN_HANG" DECIMAL(18,0) NULL,
   "CHI_NHANH" DECIMAL(18,0) NULL,
   "NGAY_HIEU_LUC" DATETIME NULL,
   "NGUOI_THU_HUONG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_EMPLOYEE_SALARY'
CREATE TABLE "dbo"."HU_EMPLOYEE_SALARY" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "BASIC_SAL" DECIMAL(18,0) NULL,
   "SOFT_SAL" DECIMAL(18,0) NULL,
   "OTHER_SAL" DECIMAL(18,0) NULL,
   "COEFFICIENT" DECIMAL(18,0) NULL,
   "CONTRACTUAL_SAL" DECIMAL(18,0) NULL,
   "SALARY_ENTERPRISE_ID" DECIMAL(18,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR(4000) NULL,
   "ALLOWANCE_SAL" DECIMAL(18,0) NULL,
   "ALLOWANCE_TOTAL" DECIMAL(18,0) NULL,
   "PERCENT_SALARY" SMALLINT NULL
);

-- Creating table 'HU_EMPLOYEE_TRAIN'
CREATE TABLE "dbo"."HU_EMPLOYEE_TRAIN" (
   "ID" DECIMAL(18,0) NOT NULL,
   "FROM_DATE" DATETIME NULL,
   "TO_DATE" DATETIME NULL,
   "SCHOOL_NAME" NVARCHAR(MAX) NULL,
   "TRAINING_FORM" DECIMAL(18,0) NULL,
   "HIGHEST_LEVEL" SMALLINT NOT NULL,
   "LEARNING_LEVEL" DECIMAL(18,0) NULL,
   "MAJOR" DECIMAL(18,0) NULL,
   "GRADUATE_YEAR" DECIMAL(18,0) NULL,
   "MARK" DECIMAL(18,0) NULL,
   "TRAINING_CONTENT" NVARCHAR(MAX) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_ORG_TITLE'
CREATE TABLE "dbo"."HU_ORG_TITLE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "DISSOLVE_DATE" DATETIME NULL,
   "FOUNDATION_DATE" DATETIME NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "HIERARCHICAL_PATH" VARCHAR(8000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "FAX" NVARCHAR(4000) NULL,
   "REPRESENTATIVE_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "TITLE_GROUP_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HU_WORKING'
CREATE TABLE "dbo"."HU_WORKING" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "STATUS_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "DECISION_TYPE_ID" DECIMAL(18,0) NULL,
   "DECISION_NO" NVARCHAR(4000) NULL,
   "SAL_GROUP_ID" DECIMAL(18,0) NULL,
   "SAL_LEVEL_ID" DECIMAL(18,0) NULL,
   "SAL_RANK_ID" DECIMAL(18,0) NULL,
   "SAL_BASIC" DECIMAL(18,0) NULL,
   "COST_SUPPORT" DECIMAL(18,0) NULL,
   "SIGN_DATE" DATETIME NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "SIGN_NAME" NVARCHAR(4000) NULL,
   "SIGN_TITLE" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "IS_PROCESS" SMALLINT NULL,
   "IS_MISSION" SMALLINT NULL,
   "IS_WAGE" SMALLINT NULL,
   "PERCENT_SALARY" DECIMAL(18,0) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" DECIMAL(18,0) NOT NULL,
   "TYPE_ID" DECIMAL(18,0) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "ATTRIBUTE1" NVARCHAR(4000) NULL,
   "ATTRIBUTE2" NVARCHAR(4000) NULL,
   "ATTRIBUTE3" NVARCHAR(4000) NULL,
   "ATTRIBUTE4" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "TYPE_CODE" NVARCHAR(4000) NULL,
   "ORDERBYID" DECIMAL(18,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "IS_SYSTEM" SMALLINT NULL,
   "TABLE_RELATION" VARCHAR(8000) NULL
);

-- Creating table 'HU_DISTRICT'
CREATE TABLE "dbo"."HU_DISTRICT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "PROVINCE_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_NATION'
CREATE TABLE "dbo"."HU_NATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_PROVINCE'
CREATE TABLE "dbo"."HU_PROVINCE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NATION_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NOT NULL
);

-- Creating table 'HU_CONTRACT'
CREATE TABLE "dbo"."HU_CONTRACT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR(4000) NULL,
   "CONTRACT_TYPE_ID" DECIMAL(18,0) NULL,
   "START_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "SIGNER_TITLE" NVARCHAR(4000) NULL,
   "SIGN_DATE" DATETIME NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "STATUS_ID" DECIMAL(18,0) NULL,
   "SIGNER_NAME" NVARCHAR(4000) NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "IS_CHALLENGE" SMALLINT NULL,
   "CHALLENGE_START" DATETIME NULL,
   "CHALLENGE_END" DATETIME NULL,
   "CHALLENGE_MONTH" SMALLINT NULL,
   "WORKING_ID" DECIMAL(18,0) NULL,
   "PERCENT_SALARY" SMALLINT NULL
);

-- Creating table 'HU_CONTRACT_TYPE'
CREATE TABLE "dbo"."HU_CONTRACT_TYPE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "PERIOD" INT NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "BHXH" DECIMAL(18,0) NULL,
   "BHYT" DECIMAL(18,0) NULL,
   "BHTN" DECIMAL(18,0) NULL,
   "BHTNLD_BNN" DECIMAL(18,0) NULL
);

-- Creating table 'HU_CONTRACT_MAX_V'
CREATE TABLE "dbo"."HU_CONTRACT_MAX_V" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CONTRACT_NO" NVARCHAR(4000) NULL,
   "CONTRACT_TYPE_ID" DECIMAL(18,0) NULL,
   "START_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "SIGNER_TITLE" NVARCHAR(4000) NULL,
   "SIGN_DATE" DATETIME NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "SIGNER_NAME" NVARCHAR(4000) NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "WORKING_ID" DECIMAL(18,0) NULL,
   "STATUS_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HU_STAFF_RANK'
CREATE TABLE "dbo"."HU_STAFF_RANK" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_ARISING'
CREATE TABLE "dbo"."INS_ARISING" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CHANGE_GROUP" DECIMAL(18,0) NULL,
   "OLD_POSNAME" NVARCHAR(4000) NULL,
   "NEW_POSNAME" NVARCHAR(4000) NULL,
   "OLD_ORGID" DECIMAL(18,0) NULL,
   "NEW_ORGID" DECIMAL(18,0) NULL,
   "OLD_SALARY" DECIMAL(18,0) NULL,
   "NEW_SALARY" DECIMAL(18,0) NULL,
   "ISBHXH" DECIMAL(18,0) NULL,
   "ISBHYT" DECIMAL(18,0) NULL,
   "ISBHTN" DECIMAL(18,0) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "DATE_CHANGE" DATETIME NULL,
   "EFFECTDATE" DATETIME NULL,
   "PKEY_REF" DECIMAL(18,0) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "REASONS" NVARCHAR(4000) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "SAL_BASE" DECIMAL(18,0) NULL,
   "WORKING_ID" DECIMAL(18,0) NULL,
   "TYPE_CHANE" DECIMAL(18,0) NULL
);

-- Creating table 'INS_CHANGE'
CREATE TABLE "dbo"."INS_CHANGE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "ORG_ID_INS" DECIMAL(18,0) NULL,
   "OLDSALARY" DECIMAL(18,0) NULL,
   "NEWSALARY" DECIMAL(18,0) NULL,
   "ISBHXH" DECIMAL(18,0) NULL,
   "ISBHYT" DECIMAL(18,0) NULL,
   "ISBHTN" DECIMAL(18,0) NULL,
   "CHANGE_TYPE" DECIMAL(18,0) NULL,
   "EFFECTDATE" DATETIME NULL,
   "CHANGE_MONTH" DATETIME NULL,
   "RETURN_DATEBHXH" DATETIME NULL,
   "RETURN_DATEBHYT" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CLTFRMMONTH" DATETIME NULL,
   "CLTTOMONTH" DATETIME NULL,
   "CLTBHXH" DECIMAL(18,0) NULL,
   "CLTBHYT" DECIMAL(18,0) NULL,
   "CLTBHTN" DECIMAL(18,0) NULL,
   "REPFRMMONTH" DATETIME NULL,
   "REPTOMONTH" DATETIME NULL,
   "REPBHXH" DECIMAL(18,0) NULL,
   "REPBHYT" DECIMAL(18,0) NULL,
   "REPBHTN" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_COST_FOLLOW_LEVER'
CREATE TABLE "dbo"."INS_COST_FOLLOW_LEVER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "COST_CODE" NVARCHAR(4000) NULL,
   "COST_NAME" NVARCHAR(4000) NULL,
   "COST_MONEY" DECIMAL(18,0) NULL,
   "EFFECTDATE_FROM" DATETIME NULL,
   "EFFECTDATE_TO" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_ENTITLED_TYPE'
CREATE TABLE "dbo"."INS_ENTITLED_TYPE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CHANGE_TYPE_ID" DECIMAL(18,0) NULL,
   "GROUP_ARISING_TYPE_ID" DECIMAL(18,0) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "DAY_OFF_SUMMARY" DECIMAL(18,0) NULL,
   "ENJOY_LEVEL" DECIMAL(18,0) NULL,
   "STATUS" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REGIME_SALARY_TYPE" DECIMAL(18,0) NULL,
   "REGIME_DAY_TYPE" DECIMAL(18,0) NULL,
   "CODE" NVARCHAR(MAX) NULL
);

-- Creating table 'INS_GROUP_REGIMES'
CREATE TABLE "dbo"."INS_GROUP_REGIMES" (
   "ID" DECIMAL(18,0) NOT NULL,
   "REGIMES_NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL
);

-- Creating table 'INS_GROUP_SUN_CARE'
CREATE TABLE "dbo"."INS_GROUP_SUN_CARE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TITLE_ID_OLD" DECIMAL(18,0) NULL,
   "TITLE_ID_NEW" DECIMAL(18,0) NULL,
   "STAFF_RANK_ID_OLD" DECIMAL(18,0) NULL,
   "STAFF_RANK_ID_NEW" DECIMAL(18,0) NULL,
   "COST_LEVER_ID_OLD" DECIMAL(18,0) NULL,
   "COST_LEVER_ID_NEW" DECIMAL(18,0) NULL,
   "EFFECTDATE_COST_NEW" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "COST_MONEY" DECIMAL(18,0) NULL
);

-- Creating table 'INS_SUN_CARE'
CREATE TABLE "dbo"."INS_SUN_CARE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "START_DATE" DATETIME NULL,
   "END_DATE" DATETIME NULL,
   "LEVEL_ID" DECIMAL(18,0) NULL,
   "COST" DECIMAL(18,0) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "THOIDIEMHUONG" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "COST_SAL" DECIMAL(18,0) NULL
);

-- Creating table 'INS_WHEREHEALTH'
CREATE TABLE "dbo"."INS_WHEREHEALTH" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NOT NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "ID_PROVINCE" DECIMAL(18,0) NULL,
   "ID_DISTRICT" DECIMAL(18,0) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "GENDER" DECIMAL(18,0) NULL,
   "IMAGE" NVARCHAR(4000) NULL,
   "BIRTH_DATE" DATETIME NULL,
   "BIRTH_PLACE" NVARCHAR(4000) NULL,
   "MARITAL_STATUS" DECIMAL(18,0) NULL,
   "RELIGION" DECIMAL(18,0) NULL,
   "NATIVE" DECIMAL(18,0) NULL,
   "NATIONALITY" DECIMAL(18,0) NULL,
   "PER_ADDRESS" NVARCHAR(4000) NULL,
   "PER_PROVINCE" DECIMAL(18,0) NULL,
   "HOME_PHONE" NVARCHAR(4000) NULL,
   "MOBILE_PHONE" NVARCHAR(4000) NULL,
   "ID_NO" NVARCHAR(4000) NULL,
   "ID_DATE" DATETIME NULL,
   "PASS_NO" NVARCHAR(4000) NULL,
   "PASS_DATE" DATETIME NULL,
   "PASS_EXPIRE" DATETIME NULL,
   "PASS_PLACE" NVARCHAR(4000) NULL,
   "VISA" NVARCHAR(4000) NULL,
   "VISA_DATE" DATETIME NULL,
   "VISA_EXPIRE" DATETIME NULL,
   "VISA_PLACE" NVARCHAR(4000) NULL,
   "WORK_PERMIT" NVARCHAR(4000) NULL,
   "WORK_PERMIT_DATE" DATETIME NULL,
   "WORK_PERMIT_EXPIRE" DATETIME NULL,
   "WORK_EMAIL" NVARCHAR(4000) NULL,
   "NAV_ADDRESS" NVARCHAR(4000) NULL,
   "NAV_PROVINCE" DECIMAL(18,0) NULL,
   "PIT_CODE" VARCHAR(8000) NULL,
   "PER_EMAIL" NVARCHAR(4000) NULL,
   "CONTACT_PER" NVARCHAR(4000) NULL,
   "CONTACT_PER_PHONE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ID_PLACE" NVARCHAR(4000) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR(4000) NULL,
   "BANK_ID" DECIMAL(18,0) NULL,
   "BANK_BRANCH_ID" DECIMAL(18,0) NULL,
   "BANK_NO" NVARCHAR(4000) NULL,
   "NGAY_VAO_DOAN" DATETIME NULL,
   "NOI_VAO_DOAN" NVARCHAR(4000) NULL,
   "CHUC_VU_DOAN" NVARCHAR(4000) NULL,
   "DOAN_PHI" SMALLINT NULL,
   "NGAY_VAO_DANG" DATETIME NULL,
   "NOI_VAO_DANG" NVARCHAR(4000) NULL,
   "CHUC_VU_DANG" NVARCHAR(4000) NULL,
   "DANG_PHI" SMALLINT NULL,
   "CAREER" NVARCHAR(4000) NULL,
   "PER_DISTRICT" DECIMAL(18,0) NULL,
   "NAV_DISTRICT" DECIMAL(18,0) NULL,
   "PER_WARD" DECIMAL(18,0) NULL,
   "NAV_WARD" DECIMAL(18,0) NULL
);

-- Creating table 'HU_WORKING_ALLOW'
CREATE TABLE "dbo"."HU_WORKING_ALLOW" (
   "ID" DECIMAL(18,0) NOT NULL,
   "HU_WORKING_ID" DECIMAL(18,0) NULL,
   "ALLOWANCE_LIST_ID" DECIMAL(18,0) NULL,
   "AMOUNT" DECIMAL(18,0) NULL,
   "IS_INSURRANCE" SMALLINT NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL
);

-- Creating table 'HU_WORKING_MAX'
CREATE TABLE "dbo"."HU_WORKING_MAX" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "STATUS_ID" DECIMAL(18,0) NULL,
   "DECISION_TYPE_ID" DECIMAL(18,0) NULL,
   "DECISION_NO" NVARCHAR(4000) NULL,
   "SAL_GROUP_ID" DECIMAL(18,0) NULL,
   "SAL_LEVEL_ID" DECIMAL(18,0) NULL,
   "SAL_RANK_ID" DECIMAL(18,0) NULL,
   "SAL_BASIC" DECIMAL(18,0) NULL,
   "COST_SUPPORT" DECIMAL(18,0) NULL,
   "SIGN_DATE" DATETIME NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "SIGN_NAME" NVARCHAR(4000) NULL,
   "SIGN_TITLE" NVARCHAR(4000) NULL,
   "IS_PROCESS" SMALLINT NULL,
   "IS_WAGE" SMALLINT NULL,
   "IS_MISSION" SMALLINT NULL,
   "PERCENT_SALARY" DECIMAL(18,0) NULL,
   "IS_3B" SMALLINT NULL,
   "STAFF_RANK_ID" DECIMAL(18,0) NULL,
   "DIRECT_MANAGER" DECIMAL(18,0) NULL
);

-- Creating table 'INS_SPECIFIED_OBJECTS'
CREATE TABLE "dbo"."INS_SPECIFIED_OBJECTS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "LOCATION_ID" DECIMAL(18,0) NULL,
   "EFFECTIVE_DATE" DATETIME NULL,
   "SI" DECIMAL(18,0) NULL,
   "HI" DECIMAL(18,0) NULL,
   "UI" DECIMAL(18,0) NULL,
   "SI_COM" DECIMAL(18,0) NULL,
   "SI_EMP" DECIMAL(18,0) NULL,
   "HI_COM" DECIMAL(18,0) NULL,
   "HI_EMP" DECIMAL(18,0) NULL,
   "UI_COM" DECIMAL(18,0) NULL,
   "UI_EMP" DECIMAL(18,0) NULL,
   "SICK" DECIMAL(18,0) NULL,
   "MATERNITY" DECIMAL(18,0) NULL,
   "OFF_IN_HOUSE" DECIMAL(18,0) NULL,
   "OFF_TOGETHER" DECIMAL(18,0) NULL,
   "RETIRE_MALE" DECIMAL(18,0) NULL,
   "RETIRE_FEMALE" DECIMAL(18,0) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "SALARY_MIN" DECIMAL(18,0) NULL,
   "SI_DATE" DECIMAL(18,0) NULL,
   "HI_DATE" DECIMAL(18,0) NULL,
   "BHTNLD_BNN_COM" DECIMAL(18,0) NULL,
   "BHTNLD_BNN_EMP" DECIMAL(18,0) NULL,
   "SI_NN" DECIMAL(18,0) NULL,
   "SI_EMP_NN" DECIMAL(18,0) NULL,
   "SI_COM_NN" DECIMAL(18,0) NULL,
   "FOREIGN" DECIMAL(18,0) NULL
);

-- Creating table 'HU_WORKING_ALLOW1'
CREATE TABLE "dbo"."HU_WORKING_ALLOW1" (
   "ID" DECIMAL(18,0) NOT NULL,
   "HU_WORKING_ID" DECIMAL(18,0) NULL,
   "ALLOWANCE_LIST_ID" DECIMAL(18,0) NULL,
   "AMOUNT" DECIMAL(18,0) NULL,
   "IS_INSURRANCE" SMALLINT NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL
);

-- Creating table 'INS_INFOOLD'
CREATE TABLE "dbo"."INS_INFOOLD" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEEID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "SALARY" DECIMAL(18,0) NULL,
   "SOFROM" DATETIME NULL,
   "SOTO" DATETIME NULL,
   "SOBOOKNO" NVARCHAR(4000) NULL,
   "SOPRVDBOOKDAY" DATETIME NULL,
   "SOWHRPRVBOOK" NVARCHAR(4000) NULL,
   "SOSTATUS_BHXH" DECIMAL(18,0) NULL,
   "HEFROM" DATETIME NULL,
   "HETO" DATETIME NULL,
   "HECARDNO" NVARCHAR(4000) NULL,
   "HEPRVDCARDDAY" DATETIME NULL,
   "HEWHRPRVCARD" NVARCHAR(4000) NULL,
   "HESTATUS_BHYT" DECIMAL(18,0) NULL,
   "HEWHRREGISKEY" NVARCHAR(4000) NULL,
   "HECARDEFFFROM" DATETIME NULL,
   "HECARDEFFTO" DATETIME NULL,
   "UEFROM" DATETIME NULL,
   "UETO" DATETIME NULL,
   "SO" DECIMAL(18,0) NULL,
   "HE" DECIMAL(18,0) NULL,
   "UE" DECIMAL(18,0) NULL,
   "REGISTER" DECIMAL(18,0) NULL,
   "CONTRACTNO" NVARCHAR(4000) NULL,
   "SENIORITY" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ORG_ID_INS" NVARCHAR(4000) NULL,
   "ISBHXH" DECIMAL(18,0) NULL,
   "ISBHYT" DECIMAL(18,0) NULL,
   "ISBHTN" DECIMAL(18,0) NULL,
   "NOTE_BHXH" NVARCHAR(4000) NULL,
   "SO_DATESENDCTY" DATETIME NULL,
   "DAYPAYMENTCOMPANY" DATETIME NULL
);

-- Creating table 'INS_INFORMATION'
CREATE TABLE "dbo"."INS_INFORMATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "INSCENTERKEY" DECIMAL(18,0) NULL,
   "SALARY" DECIMAL(18,0) NULL,
   "POSITIONNAME" NVARCHAR(4000) NULL,
   "ORGNAME" NVARCHAR(4000) NULL,
   "SOFROM" DATETIME NULL,
   "SOTO" DATETIME NULL,
   "SOBOOKNO" NVARCHAR(4000) NULL,
   "SOPRVDBOOKDAY" DATETIME NULL,
   "SOWHRPRVBOOK" NVARCHAR(4000) NULL,
   "SOPRVDBOOKSTATUS" DECIMAL(18,0) NULL,
   "HEFROM" DATETIME NULL,
   "HETO" DATETIME NULL,
   "HECARDNO" NVARCHAR(4000) NULL,
   "HEPRVDCARDDAY" DATETIME NULL,
   "HEWHRPRVCARD" NVARCHAR(4000) NULL,
   "HEPRVDCARDSTATUS" DECIMAL(18,0) NULL,
   "HEWHRREGISKEY" NVARCHAR(4000) NULL,
   "HECARDEFFFROM" DATETIME NULL,
   "HECARDEFFTO" DATETIME NULL,
   "UEFROM" DATETIME NULL,
   "UETO" DATETIME NULL,
   "SO" DECIMAL(18,0) NULL,
   "HE" DECIMAL(18,0) NULL,
   "UE" DECIMAL(18,0) NULL,
   "REGISTER" DECIMAL(18,0) NULL,
   "CONTRACTNO" NVARCHAR(4000) NULL,
   "SENIORITY" DECIMAL(18,0) NULL,
   "ORD_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "DAYPAYMENTCOMPANY" DATETIME NULL,
   "NOTE_SO" NVARCHAR(4000) NULL,
   "TOTAL_TIME_INS_BEFOR" DECIMAL(18,0) NULL
);

-- Creating table 'INS_CHANGE_TYPE'
CREATE TABLE "dbo"."INS_CHANGE_TYPE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ARISING_TYPE" DECIMAL(18,0) NULL,
   "ARISING_NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "DISPLAY_COMBO" NVARCHAR(4000) NULL,
   "SIGN_ARISING" DECIMAL(18,0) NULL,
   "SIGN_ARISING_DETAIL" DECIMAL(18,0) NULL,
   "TYPE_DECLARE_ID" DECIMAL(18,0) NULL,
   "CODE" NVARCHAR(MAX) NULL
);

-- Creating table 'INS_REMIGE_MANAGER'
CREATE TABLE "dbo"."INS_REMIGE_MANAGER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "ENTITLED_ID" DECIMAL(18,0) NULL,
   "START_DATE" DATETIME NULL,
   "END_DATE" DATETIME NULL,
   "NUM_DATE" DECIMAL(18,0) NULL,
   "DATE_OFF_BIRT" DATETIME NULL,
   "BABY_NAME" NVARCHAR(4000) NULL,
   "NUM_BABY" DECIMAL(18,0) NULL,
   "ACCUMULATED_DATE" DECIMAL(18,0) NULL,
   "ALLOWANCE_SAL" DECIMAL(18,0) NULL,
   "ALLOWANCE_MONEY" DECIMAL(18,0) NULL,
   "ALLOWANCE_MONEY_EDIT" DECIMAL(18,0) NULL,
   "TIME_ALLOWANCE" NVARCHAR(4000) NULL,
   "CONDITION_ALLOWANCE" NVARCHAR(4000) NULL,
   "SDESC" NVARCHAR(4000) NULL,
   "APPROVAL_INSURRANCE" DECIMAL(18,0) NULL,
   "APPROVAL_DATE" DATETIME NULL,
   "APPROVAL_NUM" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "IS_ATHOME" DECIMAL(18,0) NULL,
   "CHANGE_MONTH" DATETIME NULL
);

-- Creating table 'INS_REGION'
CREATE TABLE "dbo"."INS_REGION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "EFFECTIVE_DATE" DATETIME NULL,
   "AREA_ID" DECIMAL(18,0) NULL,
   "CEILING_AMOUNT" DECIMAL(18,0) NULL,
   "MIN_AMOUNT" DECIMAL(18,0) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NOT NULL,
   "PASSWORD" NVARCHAR(4000) NULL,
   "FULLNAME" NVARCHAR(4000) NOT NULL,
   "EMAIL" NVARCHAR(4000) NULL,
   "TELEPHONE" NVARCHAR(4000) NULL,
   "LOCATION" NVARCHAR(4000) NULL,
   "IS_APP" SMALLINT NOT NULL,
   "IS_PORTAL" SMALLINT NOT NULL,
   "EMPLOYEE_CODE" VARCHAR(8000) NULL,
   "IS_AD" SMALLINT NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "IS_CHANGE_PASS" SMALLINT NULL,
   "CHANGE_PASS_DATE" DATETIME NULL,
   "REMINDER_COUNT" SMALLINT NULL,
   "MODULE_ADMIN" NVARCHAR(4000) NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "CODE" NVARCHAR(4000) NOT NULL,
   "MODULE_ID" DECIMAL(18,0) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL
);

-- Creating table 'INS_LIST_PROGRAM'
CREATE TABLE "dbo"."INS_LIST_PROGRAM" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL,
   "ACTFLG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_LIST_CONTRACT'
CREATE TABLE "dbo"."INS_LIST_CONTRACT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CONTRACT_INS_NO" NVARCHAR(4000) NULL,
   "YEAR" DECIMAL(18,0) NULL,
   "ORG_INSURANCE" DECIMAL(18,0) NULL,
   "START_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "VAL_CO" DECIMAL(18,0) NULL,
   "BUY_DATE" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "PROGRAM_ID" DECIMAL(18,0) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_LIST_CONTRACT_DETAIL'
CREATE TABLE "dbo"."INS_LIST_CONTRACT_DETAIL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CONTRACT_INS_ID" DECIMAL(18,0) NULL,
   "INS_PROGRAM_ID" DECIMAL(18,0) NULL,
   "MONEY_INS" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL
);

-- Creating table 'INS_TYPE_CHANGE'
CREATE TABLE "dbo"."INS_TYPE_CHANGE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL
);

-- Creating table 'INS_LIST_INSURANCE'
CREATE TABLE "dbo"."INS_LIST_INSURANCE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "TREATMENTCODE" NVARCHAR(4000) NULL,
   "PHONE_NUMBER" NVARCHAR(4000) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "PROVINCECODE" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL
);

-- Creating table 'INS_CHANGE_INFO'
CREATE TABLE "dbo"."INS_CHANGE_INFO" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TYPE_CHANGE_ID" DECIMAL(18,0) NULL,
   "DATE_CHANGE" DATETIME NULL,
   "CONTENT_CHANGE" NVARCHAR(4000) NULL,
   "OLD_INFO" NVARCHAR(4000) NULL,
   "NEW_INFO" NVARCHAR(4000) NULL,
   "REASON_CHANGE" NVARCHAR(4000) NULL,
   "MONTH_DECLARE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'INS_CLAIME_INSURANCE'
CREATE TABLE "dbo"."INS_CLAIME_INSURANCE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "SUN_CARE_ID" DECIMAL(18,0) NULL,
   "EXAMINE_DATE" DATETIME NULL,
   "DISEASE_NAME" NVARCHAR(4000) NULL,
   "AMOUNT_OF_CLAIMS" DECIMAL(18,0) NULL,
   "AMOUNT_OF_COMPENSATION" DECIMAL(18,0) NULL,
   "COMPENSATION_DATE" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "INS_HEALTH_ID" DECIMAL(18,0) NULL
);

-- Creating table 'INS_HEALTH_INSURANCE'
CREATE TABLE "dbo"."INS_HEALTH_INSURANCE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "YEAR" DECIMAL(18,0) NULL,
   "INS_CONTRACT_ID" DECIMAL(18,0) NULL,
   "CHECK_BHNT" DECIMAL(18,0) NULL,
   "FAMYLI_ID" DECIMAL(18,0) NULL,
   "DT_CHITRA" DECIMAL(18,0) NULL,
   "JOIN_DATE" DATETIME NULL,
   "EFFECT_DATE" DATETIME NULL,
   "MONEY_INS" DECIMAL(18,0) NULL,
   "REDUCE_DATE" DATETIME NULL,
   "REFUND" DECIMAL(18,0) NULL,
   "DATE_RECEIVE_MONEY" DATETIME NULL,
   "EMP_RECEIVE_MONEY" NVARCHAR(4000) NULL,
   "NOTES" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "INS_CONTRACT_DE_ID" DECIMAL(18,0) NULL
);

-- Creating table 'INS_REGIMES'
CREATE TABLE "dbo"."INS_REGIMES" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "REGIME_ID" DECIMAL(18,0) NULL,
   "PAY_FORM" DECIMAL(18,0) NULL,
   "FROM_DATE" DATETIME NULL,
   "TO_DATE" DATETIME NULL,
   "DAY_CALCULATOR" DECIMAL(18,0) NULL,
   "BORN_DATE" DATETIME NULL,
   "NAME_CHILDREN" NVARCHAR(4000) NULL,
   "CHILDREN_NO" DECIMAL(18,0) NULL,
   "ACCUMULATE_DAY" DECIMAL(18,0) NULL,
   "SUBSIDY_SALARY" DECIMAL(18,0) NULL,
   "SUBSIDY_AMOUNT" DECIMAL(18,0) NULL,
   "PAYROLL_DATE" DATETIME NULL,
   "CONDITION" NVARCHAR(4000) NULL,
   "INS_PAY_AMOUNT" DECIMAL(18,0) NULL,
   "PAY_APPROVE_DATE" DATETIME NULL,
   "APPROV_DAY_NUM" DECIMAL(18,0) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "MONEY_ADVANCE" DECIMAL(18,0) NULL,
   "DECLARE_DATE" DATETIME NULL,
   "SUBSIDY" DECIMAL(18,0) NULL,
   "IS_DELETED" DECIMAL(18,0) NULL,
   "OFF_IN_HOUSE" DECIMAL(18,0) NULL,
   "OFF_TOGETHER" DECIMAL(18,0) NULL,
   "SUBSIDY_MODIFY" DECIMAL(18,0) NULL,
   "REGIMES_SAL" DECIMAL(18,0) NULL,
   "FORM_ALLOW" DECIMAL(18,0) NULL
);

-- Creating table 'AT_TIME_MANUAL'
CREATE TABLE "dbo"."AT_TIME_MANUAL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "MORNING_ID" DECIMAL(18,0) NULL,
   "AFTERNOON_ID" DECIMAL(18,0) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ORDER_W" DECIMAL(18,0) NULL,
   "LIMIT_DAY" NVARCHAR(4000) NULL,
   "LIMIT_YEAR" NVARCHAR(4000) NULL,
   "TYPE_PROSS_ID" DECIMAL(18,0) NULL,
   "MORNING_RATE_ID" DECIMAL(18,0) NULL,
   "AFTERNOON_RATE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "ORDERS" DECIMAL(18,0) NULL,
   "MAPPING_CODE" NVARCHAR(4000) NULL,
   "IS_OTHER" SMALLINT NULL,
   "INS_ID" DECIMAL(18,0) NULL
);

-- Creating table 'INS_ARISING_LEAVESHEET'
CREATE TABLE "dbo"."INS_ARISING_LEAVESHEET" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "INS_ORG_ID" DECIMAL(18,0) NULL,
   "MANUAL_ID" DECIMAL(18,0) NULL,
   "LEAVE_FROM" DATETIME NULL,
   "LEAVE_TO" DATETIME NULL,
   "DAY_NUM" DECIMAL(18,0) NULL,
   "FROM_MONTH" DATETIME NULL,
   "TO_MONTH" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'AT_FML'
CREATE TABLE "dbo"."AT_FML" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "IS_LEAVE" DECIMAL(18,0) NULL,
   "IS_CALHOLIDAY" DECIMAL(18,0) NULL,
   "HOURS" DECIMAL(18,0) NULL,
   "IS_REG_SHIFT" DECIMAL(18,0) NULL,
   "IS_SALARY" DECIMAL(18,0) NULL,
   "DAY_NUM" DECIMAL(18,0) NULL,
   "IS_BHXH" DECIMAL(18,0) NULL,
   "IS_NOTIFY" DECIMAL(18,0) NULL
);

-- Creating table 'AT_TYPE_PROCESS'
CREATE TABLE "dbo"."AT_TYPE_PROCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL
);

-- Creating table 'INS_WORKING_BEFORE'
CREATE TABLE "dbo"."INS_WORKING_BEFORE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "FROM_MONTH" DATETIME NULL,
   "TO_MONTH" DATETIME NULL,
   "COMPANY" NVARCHAR(4000) NULL,
   "TITLE" NVARCHAR(4000) NULL,
   "INS_SALARY" DECIMAL(18,0) NULL,
   "SALARY" DECIMAL(18,0) NULL,
   "TOXIC" DECIMAL(18,0) NULL,
   "COEFFICIENT" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" DECIMAL(18,0) NOT NULL,
   "SE_USER_ID" DECIMAL(18,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "PK_HU_EMPLOYEE_EDUCATION"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "PK_HU_EMPLOYEE_FILES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "PK_HU_EMPLOYEE_HEALTH"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "PK_HU_EMPLOYEE_OTHER_INFO"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "PK_HU_EMPLOYEE_SALARY"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE_TRAIN'
ALTER TABLE "dbo"."HU_EMPLOYEE_TRAIN"
ADD CONSTRAINT "PK_HU_EMPLOYEE_TRAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "PK_HU_ORG_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "PK_HU_WORKING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "PK_HU_DISTRICT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_NATION'
ALTER TABLE "dbo"."HU_NATION"
ADD CONSTRAINT "PK_HU_NATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "PK_HU_PROVINCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT'
ALTER TABLE "dbo"."HU_CONTRACT"
ADD CONSTRAINT "PK_HU_CONTRACT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_TYPE'
ALTER TABLE "dbo"."HU_CONTRACT_TYPE"
ADD CONSTRAINT "PK_HU_CONTRACT_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_CONTRACT_MAX_V'
ALTER TABLE "dbo"."HU_CONTRACT_MAX_V"
ADD CONSTRAINT "PK_HU_CONTRACT_MAX_V"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_STAFF_RANK'
ALTER TABLE "dbo"."HU_STAFF_RANK"
ADD CONSTRAINT "PK_HU_STAFF_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ARISING'
ALTER TABLE "dbo"."INS_ARISING"
ADD CONSTRAINT "PK_INS_ARISING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CHANGE'
ALTER TABLE "dbo"."INS_CHANGE"
ADD CONSTRAINT "PK_INS_CHANGE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_COST_FOLLOW_LEVER'
ALTER TABLE "dbo"."INS_COST_FOLLOW_LEVER"
ADD CONSTRAINT "PK_INS_COST_FOLLOW_LEVER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ENTITLED_TYPE'
ALTER TABLE "dbo"."INS_ENTITLED_TYPE"
ADD CONSTRAINT "PK_INS_ENTITLED_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_GROUP_REGIMES'
ALTER TABLE "dbo"."INS_GROUP_REGIMES"
ADD CONSTRAINT "PK_INS_GROUP_REGIMES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_GROUP_SUN_CARE'
ALTER TABLE "dbo"."INS_GROUP_SUN_CARE"
ADD CONSTRAINT "PK_INS_GROUP_SUN_CARE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_SUN_CARE'
ALTER TABLE "dbo"."INS_SUN_CARE"
ADD CONSTRAINT "PK_INS_SUN_CARE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_WHEREHEALTH'
ALTER TABLE "dbo"."INS_WHEREHEALTH"
ADD CONSTRAINT "PK_INS_WHEREHEALTH"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_ALLOW'
ALTER TABLE "dbo"."HU_WORKING_ALLOW"
ADD CONSTRAINT "PK_HU_WORKING_ALLOW"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_MAX'
ALTER TABLE "dbo"."HU_WORKING_MAX"
ADD CONSTRAINT "PK_HU_WORKING_MAX"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_SPECIFIED_OBJECTS'
ALTER TABLE "dbo"."INS_SPECIFIED_OBJECTS"
ADD CONSTRAINT "PK_INS_SPECIFIED_OBJECTS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING_ALLOW1'
ALTER TABLE "dbo"."HU_WORKING_ALLOW1"
ADD CONSTRAINT "PK_HU_WORKING_ALLOW1"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_INFOOLD'
ALTER TABLE "dbo"."INS_INFOOLD"
ADD CONSTRAINT "PK_INS_INFOOLD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_INFORMATION'
ALTER TABLE "dbo"."INS_INFORMATION"
ADD CONSTRAINT "PK_INS_INFORMATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CHANGE_TYPE'
ALTER TABLE "dbo"."INS_CHANGE_TYPE"
ADD CONSTRAINT "PK_INS_CHANGE_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REMIGE_MANAGER'
ALTER TABLE "dbo"."INS_REMIGE_MANAGER"
ADD CONSTRAINT "PK_INS_REMIGE_MANAGER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REGION'
ALTER TABLE "dbo"."INS_REGION"
ADD CONSTRAINT "PK_INS_REGION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_LIST_PROGRAM'
ALTER TABLE "dbo"."INS_LIST_PROGRAM"
ADD CONSTRAINT "PK_INS_LIST_PROGRAM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_LIST_CONTRACT'
ALTER TABLE "dbo"."INS_LIST_CONTRACT"
ADD CONSTRAINT "PK_INS_LIST_CONTRACT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_LIST_CONTRACT_DETAIL'
ALTER TABLE "dbo"."INS_LIST_CONTRACT_DETAIL"
ADD CONSTRAINT "PK_INS_LIST_CONTRACT_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_TYPE_CHANGE'
ALTER TABLE "dbo"."INS_TYPE_CHANGE"
ADD CONSTRAINT "PK_INS_TYPE_CHANGE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_LIST_INSURANCE'
ALTER TABLE "dbo"."INS_LIST_INSURANCE"
ADD CONSTRAINT "PK_INS_LIST_INSURANCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CHANGE_INFO'
ALTER TABLE "dbo"."INS_CHANGE_INFO"
ADD CONSTRAINT "PK_INS_CHANGE_INFO"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_CLAIME_INSURANCE'
ALTER TABLE "dbo"."INS_CLAIME_INSURANCE"
ADD CONSTRAINT "PK_INS_CLAIME_INSURANCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_HEALTH_INSURANCE'
ALTER TABLE "dbo"."INS_HEALTH_INSURANCE"
ADD CONSTRAINT "PK_INS_HEALTH_INSURANCE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_REGIMES'
ALTER TABLE "dbo"."INS_REGIMES"
ADD CONSTRAINT "PK_INS_REGIMES"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_MANUAL'
ALTER TABLE "dbo"."AT_TIME_MANUAL"
ADD CONSTRAINT "PK_AT_TIME_MANUAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_ARISING_LEAVESHEET'
ALTER TABLE "dbo"."INS_ARISING_LEAVESHEET"
ADD CONSTRAINT "PK_INS_ARISING_LEAVESHEET"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_FML'
ALTER TABLE "dbo"."AT_FML"
ADD CONSTRAINT "PK_AT_FML"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TYPE_PROCESS'
ALTER TABLE "dbo"."AT_TYPE_PROCESS"
ADD CONSTRAINT "PK_AT_TYPE_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'INS_WORKING_BEFORE'
ALTER TABLE "dbo"."INS_WORKING_BEFORE"
ADD CONSTRAINT "PK_INS_WORKING_BEFORE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_HEALTH'
ALTER TABLE "dbo"."HU_EMPLOYEE_HEALTH"
ADD CONSTRAINT "FK_FE_HEH"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_EDUCATION'
ALTER TABLE "dbo"."HU_EMPLOYEE_EDUCATION"
ADD CONSTRAINT "FK_HE_HEE"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_FILES'
ALTER TABLE "dbo"."HU_EMPLOYEE_FILES"
ADD CONSTRAINT "FK_HE_HEF"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HEF'
CREATE INDEX "IX_FK_HE_HEF"
ON "dbo"."HU_EMPLOYEE_FILES"
   ("EMPLOYEE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_OTHER_INFO'
ALTER TABLE "dbo"."HU_EMPLOYEE_OTHER_INFO"
ADD CONSTRAINT "FK_HE_HEO"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_EMPLOYEE_SALARY'
ALTER TABLE "dbo"."HU_EMPLOYEE_SALARY"
ADD CONSTRAINT "FK_HE_HES"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating foreign key on "TITLE_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HE_HT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HT'
CREATE INDEX "IX_FK_HE_HT"
ON "dbo"."HU_EMPLOYEE"
   ("TITLE_ID");

-- Creating foreign key on "EMPLOYEE_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HE_HW"
   FOREIGN KEY ("EMPLOYEE_ID")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HE_HW'
CREATE INDEX "IX_FK_HE_HW"
ON "dbo"."HU_WORKING"
   ("EMPLOYEE_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "DIRECT_MANAGER" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HUEMD_HUEM"
   FOREIGN KEY ("DIRECT_MANAGER")
   REFERENCES "dbo"."HU_EMPLOYEE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUEMD_HUEM'
CREATE INDEX "IX_FK_HUEMD_HUEM"
ON "dbo"."HU_EMPLOYEE"
   ("DIRECT_MANAGER");

-- Creating foreign key on "ORG_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUOG_HUOT"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUOT'
CREATE INDEX "IX_FK_HUOG_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_ORG_TITLE'
ALTER TABLE "dbo"."HU_ORG_TITLE"
ADD CONSTRAINT "FK_HUTL_HUOT"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUOT'
CREATE INDEX "IX_FK_HUTL_HUOT"
ON "dbo"."HU_ORG_TITLE"
   ("TITLE_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUOG_HUWK"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUOG_HUWK'
CREATE INDEX "IX_FK_HUOG_HUWK"
ON "dbo"."HU_WORKING"
   ("ORG_ID");

-- Creating foreign key on "TITLE_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_HUTL_HUWK"
   FOREIGN KEY ("TITLE_ID")
   REFERENCES "dbo"."HU_TITLE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HUTL_HUWK'
CREATE INDEX "IX_FK_HUTL_HUWK"
ON "dbo"."HU_WORKING"
   ("TITLE_ID");

-- Creating foreign key on "STATUS_ID" in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "FK_OTOTL_HUWK"
   FOREIGN KEY ("STATUS_ID")
   REFERENCES "dbo"."OT_OTHER_LIST"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OTOTL_HUWK'
CREATE INDEX "IX_FK_OTOTL_HUWK"
ON "dbo"."HU_WORKING"
   ("STATUS_ID");

-- Creating foreign key on "TYPE_ID" in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "FK_OOLT_OOL"
   FOREIGN KEY ("TYPE_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_TYPE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLT_OOL'
CREATE INDEX "IX_FK_OOLT_OOL"
ON "dbo"."OT_OTHER_LIST"
   ("TYPE_ID");

-- Creating foreign key on "GROUP_ID" in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "FK_OOLG_OOLT"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLG_OOLT'
CREATE INDEX "IX_FK_OOLG_OOLT"
ON "dbo"."OT_OTHER_LIST_TYPE"
   ("GROUP_ID");

-- Creating foreign key on "PROVINCE_ID" in table 'HU_DISTRICT'
ALTER TABLE "dbo"."HU_DISTRICT"
ADD CONSTRAINT "FK_HU_PRO_HU_DIS"
   FOREIGN KEY ("PROVINCE_ID")
   REFERENCES "dbo"."HU_PROVINCE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_PRO_HU_DIS'
CREATE INDEX "IX_FK_HU_PRO_HU_DIS"
ON "dbo"."HU_DISTRICT"
   ("PROVINCE_ID");

-- Creating foreign key on "NATION_ID" in table 'HU_PROVINCE'
ALTER TABLE "dbo"."HU_PROVINCE"
ADD CONSTRAINT "FK_HU_NAT_HU_PRO"
   FOREIGN KEY ("NATION_ID")
   REFERENCES "dbo"."HU_NATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_NAT_HU_PRO'
CREATE INDEX "IX_FK_HU_NAT_HU_PRO"
ON "dbo"."HU_PROVINCE"
   ("NATION_ID");

-- Creating foreign key on "SE_REPORT_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_REPORT"
   FOREIGN KEY ("SE_REPORT_ID")
   REFERENCES "dbo"."SE_REPORT"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_REPORT'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_REPORT"
ON "dbo"."SE_USER_REPORT"
   ("SE_REPORT_ID");

-- Creating foreign key on "SE_USER_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_USER"
   FOREIGN KEY ("SE_USER_ID")
   REFERENCES "dbo"."SE_USER"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_USER'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_USER"
ON "dbo"."SE_USER_REPORT"
   ("SE_USER_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
