Public Class TitleDTO
    Public Property JOB_NAME As String
    Public Property ORG_NAME As String
    Public Property IS_UYBAN As Boolean?
    Public Property ORG_DESC As String
    Public Property IS_OWNER As Boolean?
    Public Property EFFECTIVE_DATE As Date?
    Public Property MASTER_NAME As String
    Public Property LM_CODE As String
    Public Property LM As Decimal?
    Public Property TEXTBOX2_SEARCH As String
    Public Property ID As Decimal
    Public Property CODE As String
    Public Property NAME_SUM As String
    Public Property NAME_EN As String
    Public Property NAME_VN As String
    Public Property TITLE_GROUP_ID As Decimal?
    Public Property TITLE_GROUP_NAME As String
    Public Property TITLE_GROUP_CODE As String
    Public Property REMARK As String
    Public Property ACTFLG As String
    Public Property CREATED_DATE As Date
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property WORK_INVOLVE_NAME As String
    Public Property UPLOAD_FILE As String
    Public Property LEVEL_ID As Decimal?
    Public Property LEVEL_TITLE_NAME As String
    Public Property DRIVE_INFOR_CHECK As Boolean


    Public Property HURTFUL As Decimal?
    Public Property HURTFUL_CHECK As Boolean
    Public Property SPEC_HURFUL As Decimal?
    Public Property SPEC_HURFUL_CHECK As Boolean
    Public Property HURT_TYPE_ID As Decimal?
    Public Property HURT_TYPE_NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_ID_NAME As String
    Public Property ORG_TYPE As Decimal?
    Public Property ORG_TYPE_NAME As String
    Public Property TITLE_GROUP_ID1 As Decimal?

    Public Property OVT As Decimal?
    Public Property OVT_CHECK As Boolean
    Public Property WORK_INVOLVE_ID As Boolean
    Public Property DRIVE_INFOR As Boolean
    Public Property LIST_PC_ID As Boolean
    Public Property GROUP_EMPLOYEE_ID As Decimal?
    Public Property GROUP_EMPLOYEE_NAME As String

    Public Property TN_COEF As Decimal?
    Public Property CV_COEF As Decimal?
    Public Property IS_CBCD As Boolean?
    Public Property IS_PERCENT As Boolean?
    Public Property TITLE_BLD_ID As Decimal?
    Public Property TITLE_BLD_NAME As String
    Public Property TITLE_TBL_ID As Decimal?
    Public Property TITLE_TBL_NAME As String

    Public Property CHUCVU_ID As Decimal?
    Public Property CHUCVU_NAME As String
    Public Property INTERIM_NAME As String
    Public Property CSM_CODE As String
    Public Property ORG_ID_SEARCH As Decimal?
    Public Property IS_NONPHYSICAL As Boolean
    Public Property IS_PLAN As Boolean
    Public Property COST_CENTER As String
    Public Property MASTER As Decimal?
    Public Property INTERIM As Decimal?
    Public Property BOTH As Integer
    Public Property COLOR As String
    Public Property CSM_NAME As String
    Public Property CSM As Decimal?
    Public Property LM_NAME As String
    Public Property IS_PLAN_LEFT As Integer
    Public Property ORG_ID2_SEARCH As Decimal?
    Public Property MASTER_CODE As String
    Public Property HIRING_STATUS As Short?
    Public Property CONCURRENT As Short?
    Public Property JOB_ID As Decimal?
    Public Property FLAG As Integer
    Public Property TEXTBOX_SEARCH As String
    Public Property SOLUONG As Decimal?
    Public Property WORK_LOCATION As Decimal?
    Public Property WORK_LOCATION_NAME As String
    Public Property JOB_SPEC As String
    Public Property JOB_BAND_NAME As String

    Public Property EMP_LM As String
    Public Property EMP_CSM As String

    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_NAME As String
    Public Property EMPLOYEE_CODE As String

    Public Property UPLOADFILE As String
    Public Property FILENAME As String

    Public Property PHAN_LOAI_ID As Decimal?
    Public Property PHAN_LOAI_NAME As String
    Public Property WORKING_TIME As Decimal?
    Public Property WORKING_TIME_NAME As String
    Public Property Is_Vacant As Boolean?
    Public Property IS_INTERIM As Decimal?
    Public Property IS_MASTER As Decimal?
    Public Property IS_CONCURRENTLY As Decimal?
    Public Property JobDescription As JobDescriptionDTO
    Public Property FILE_LOGO As String
    Public Property ATTACH_FILE_LOGO As String
End Class
Public Class JobDescriptionDTO
    Public Property ID As Decimal?
    Public Property JOB_TARGET_1 As String
    Public Property JOB_TARGET_2 As String
    Public Property JOB_TARGET_3 As String
    Public Property JOB_TARGET_4 As String
    Public Property JOB_TARGET_5 As String
    Public Property JOB_TARGET_6 As String
    Public Property TDCM As Decimal?
    Public Property TDCM_NAME As String
    Public Property MAJOR As Decimal?
    Public Property MAJOR_NAME As String
    Public Property WORK_EXP As String
    Public Property LANGUAGE As Decimal?
    Public Property LANGUAGE_NAME As String
    Public Property COMPUTER As Decimal?
    Public Property COMPUTER_NAME As String
    Public Property SUPPORT_SKILL As String
    Public Property INTERNAL_1 As String
    Public Property INTERNAL_2 As String
    Public Property INTERNAL_3 As String
    Public Property OUTSIDE_1 As String
    Public Property OUTSIDE_2 As String
    Public Property OUTSIDE_3 As String
    Public Property RESPONSIBILITY_1 As String
    Public Property RESPONSIBILITY_2 As String
    Public Property RESPONSIBILITY_3 As String
    Public Property RESPONSIBILITY_4 As String
    Public Property RESPONSIBILITY_5 As String
    Public Property DETAIL_RESPONSIBILITY_1 As String
    Public Property DETAIL_RESPONSIBILITY_2 As String
    Public Property DETAIL_RESPONSIBILITY_3 As String
    Public Property DETAIL_RESPONSIBILITY_4 As String
    Public Property DETAIL_RESPONSIBILITY_5 As String
    Public Property OUT_RESULT_1 As String
    Public Property OUT_RESULT_2 As String
    Public Property OUT_RESULT_3 As String
    Public Property OUT_RESULT_4 As String
    Public Property OUT_RESULT_5 As String
    Public Property PERMISSION_1 As String
    Public Property PERMISSION_2 As String
    Public Property PERMISSION_3 As String
    Public Property PERMISSION_4 As String
    Public Property PERMISSION_5 As String
    Public Property PERMISSION_6 As String
    Public Property FILE_NAME As String
    Public Property UPLOAD_FILE As String
    Public Property TITLE_ID As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
End Class