Public Class AT_OT_REGISTRATIONDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property HS_NAME As String
    Public Property FULLNAME As String
    Public Property DEPARTMENT_ID As Decimal?
    Public Property DEPARTMENT_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property REGIST_DATE As Date?
    Public Property SIGN_ID As Decimal?
    Public Property SIGN_CODE As String
    Public Property OT_TYPE_ID As Decimal?
    Public Property OT_TYPE_NAME As String
    Public Property FROM_AM As Decimal?
    Public Property FROM_AM_MN As Decimal?
    Public Property TO_AM As Decimal?
    Public Property TO_AM_MN As Decimal?
    Public Property FROM_PM As Decimal?
    Public Property FROM_PM_MN As Decimal?
    Public Property TO_PM As Decimal?
    Public Property TO_PM_MN As Decimal?
    Public Property TOTAL_OT As Decimal?
    Public Property TOTAL_OT_STR As String
    Public Property OT_100 As Decimal?
    Public Property OT_150 As Decimal?
    Public Property OT_180 As Decimal?
    Public Property OT_200 As Decimal?
    Public Property OT_210 As Decimal?
    Public Property OT_270 As Decimal?
    Public Property OT_300 As Decimal?
    Public Property OT_370 As Decimal?
    Public Property NOTE As String
    Public Property STATUS As Decimal?
    Public Property STATUS_NAME As String
    Public Property REASON As String
    Public Property IS_DELETED As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property MODIFIED_NAME As String
    Public Property P_LANG As String
    Public Property P_USER As String
    Public Property P_MANAGER As String
    Public Property P_MANAGER_ID As Decimal?
    Public Property P_GM As String
    Public Property P_GM_ID As Decimal?
    Public Property REGIST_DATE_FROM As Date?
    Public Property REGIST_DATE_TO As Date?
    Public Property HR_REVIEW As String
    Public Property ID_REGGROUP As Decimal?
    Public Property FROM_HOUR_AM As String
    Public Property TO_HOUR_AM As String
    Public Property FROM_HOUR_PM As String
    Public Property TO_HOUR_PM As String
    Public Property IS_TER As Boolean?
    Public Property HOURS_TOTAL_AM As Decimal?
    Public Property HOURS_TOTAL_PM As Decimal?
    Public Property HOURS_TOTAL_DAY As Decimal?
    Public Property HOURS_TOTAL_NIGHT As Decimal?

    Public Property HOURS_TOTAL_AM_STR As String
    Public Property HOURS_TOTAL_PM_STR As String
    Public Property HOURS_TOTAL_DAY_STR As String
    Public Property HOURS_TOTAL_NIGHT_STR As String

    Public Property PM_FROMHOURS_AFTERCHECK As Decimal?
    Public Property PM_TOHOURS_AFTERCHECK As Decimal?
    Public Property PM_FROMHOURS_AFTERCHECK_STR As String
    Public Property PM_TOHOURS_AFTERCHECK_STR As String
    Public Property ORG_OT_ID_NAME As String
    Public Property ORG_OT_ID_DESC As String
    Public Property ORG_OT_ID As Decimal?
    Public Property DK_PORTAL As Decimal?
    Public Property CREATED_BY_EMP As Decimal?
    Public Property CONFIRM_OT_TT As Decimal?
    Public Property TOTAL_DAY_TH As Decimal?
    Public Property TOTAL_NIGHT_TH As Decimal?
    Public Property TOTAL_OT_TH As Decimal?
    Public Property TOTAL_DAY_TT As Decimal?
    Public Property TOTAL_NIGHT_TT As Decimal?
    Public Property TOTAL_OT_TT As Decimal?
    Public Property CHECKIN_TT As Date?
    Public Property CHECKOUT_TT As Date?
    Public Property PERIOD_ID As Decimal?
    Public Property BY_ANOTHER As Boolean?
    Public Property PERIOD_NAME As String
    Public Property P_LST_ID As String
    Public Property IS_PASS_DAY As Decimal?
    Public Property USERID As Decimal?
    Public Property ACTION As Decimal?
    Public Property IDGROUPS As String
    Public Property COMMENT As String
    Public Property ID_HS As Decimal?
End Class