Public Class AT_SENIORITYDTO
    Public Property ID As Decimal?
    Public Property EFFECTDATE As Date?
    Public Property NOTE As String
    Public Property YEAR1 As Decimal?
    Public Property YEAR2 As Decimal?
    Public Property YEAR3 As Decimal?
    Public Property YEAR4 As Decimal?
    Public Property YEAR5 As Decimal?
    Public Property YEAR6 As Decimal?
    Public Property YEAR7 As Decimal?
    Public Property YEAR8 As Decimal?
    Public Property YEAR9 As Decimal?
    Public Property YEAR10 As Decimal?
    Public Property YEAR11 As Decimal?
    Public Property YEAR12 As Decimal?
    Public Property YEAR13 As Decimal?
    Public Property YEAR14 As Decimal?
    Public Property YEAR15 As Decimal?
    Public Property YEAR16 As Decimal?
    Public Property YEAR17 As Decimal?
    Public Property YEAR18 As Decimal?
    Public Property YEAR19 As Decimal?
    Public Property YEAR20 As Decimal?
    Public Property YEAR21 As Decimal?
    Public Property YEAR22 As Decimal?
    Public Property YEAR23 As Decimal?
    Public Property YEAR24 As Decimal?
    Public Property YEAR25 As Decimal?
    Public Property YEAR26 As Decimal?
    Public Property YEAR27 As Decimal?
    Public Property YEAR28 As Decimal?
    Public Property YEAR29 As Decimal?
    Public Property YEAR30 As Decimal?
    Public Property YEAR31 As Decimal?
    Public Property YEAR32 As Decimal?
    Public Property YEAR33 As Decimal?
    Public Property YEAR34 As Decimal?
    Public Property YEAR35 As Decimal?
    Public Property YEAR36 As Decimal?
    Public Property YEAR37 As Decimal?
    Public Property YEAR38 As Decimal?
    Public Property YEAR39 As Decimal?
    Public Property YEAR40 As Decimal?
    Public Property YEAR41 As Decimal?
    Public Property YEAR42 As Decimal?
    Public Property YEAR43 As Decimal?
    Public Property YEAR44 As Decimal?
    Public Property YEAR45 As Decimal?
    Public Property YEAR46 As Decimal?
    Public Property YEAR47 As Decimal?
    Public Property YEAR48 As Decimal?
    Public Property YEAR49 As Decimal?
    Public Property YEAR50 As Decimal?
    Public Property YEAR51 As Decimal?
    Public Property YEAR52 As Decimal?
    Public Property YEAR53 As Decimal?
    Public Property YEAR54 As Decimal?
    Public Property YEAR55 As Decimal?
    Public Property YEAR56 As Decimal?
    Public Property YEAR57 As Decimal?
    Public Property YEAR58 As Decimal?
    Public Property YEAR59 As Decimal?
    Public Property YEAR60 As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String

End Class
