Public Class AT_SETUP_ELEAVEDTO
    Public Property ID As Decimal
    Public Property EFFECT_YEAR As Decimal?
    Public Property ANNUAL_YEAR As Decimal?
    Public Property ANNUAL_MONTH As Decimal?
    Public Property OFFICIAL_DATE As Decimal?
    Public Property START_DATE As Decimal?
    Public Property ANNUAL_YEAR_NAME As String
    Public Property ANNUAL_MONTH_NAME As String
    Public Property OFFICIAL_DATE_NAME As String
    Public Property START_DATE_NAME As String
    Public Property OLDANNUAL_TIME As String
    Public Property OLDANNUAL_RENEW As String
    Public Property ANNUAL_TRANSFER As Decimal?
    Public Property ANNUAL_PAID As Decimal?
    Public Property STARTDATE_FROM1 As Decimal?
    Public Property STARTDATE_TO1 As Decimal?
    Public Property ANNUAL_START1 As Decimal?
    Public Property STARTDATE_FROM2 As Decimal?
    Public Property STARTDATE_TO2 As Decimal?
    Public Property ANNUAL_START2 As Decimal?
    Public Property LEAVEDATE_FROM1 As Decimal?
    Public Property LEAVEDATE_TO1 As Decimal?
    Public Property ANNUAL_LEAVE1 As Decimal?
    Public Property LEAVEDATE_FROM2 As Decimal?
    Public Property LEAVEDATE_TO2 As Decimal?
    Public Property ANNUAL_LEAVE2 As Decimal?
    Public Property WORKDATE_FROM1 As Decimal?
    Public Property WORKDATE_TO1 As Decimal?
    Public Property ANNUAL_WORK1 As Decimal?
    Public Property WORKDATE_FROM2 As Decimal?
    Public Property WORKDATE_TO2 As Decimal?
    Public Property ANNUAL_WORK2 As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property OLDANNUAL_TIME_BU As String
    Public Property OLDANNUAL_RENEW_BU As String
    Public Property ANNUAL_TRANSFER_BU As Decimal?
End Class
