Public Class AT_TIME_TIMESHEET_MONTHLYDTO
    Public Property ID As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property VN_FULLNAME As String
    Public Property EMPLOYEE_CODE As String
    Public Property WORKINGDAY As Date?
    Public Property JOIN_DATE As Date?
    Public Property PERIOD_STANDARD As Decimal?
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property IS_DISSOLVE As Boolean
    Public Property TITLE_NAME As String
    Public Property DECISION_START As Date?
    Public Property DECISION_END As Date?
    Public Property PERIOD_ID As Decimal?
    Public Property FROM_DATE As Date?
    Public Property END_DATE As Date?
    Public Property STAFF_RANK_NAME As String
    Public Property WORKING_X As Decimal?
    Public Property WORKING_F As Decimal?
    Public Property WORKING_E As Decimal?
    Public Property WORKING_A As Decimal?
    Public Property WORKING_H As Decimal?
    Public Property WORKING_D As Decimal?
    Public Property WORKING_C As Decimal?
    Public Property WORKING_T As Decimal?
    Public Property WORKING_Q As Decimal?
    Public Property WORKING_N As Decimal?
    Public Property WORKING_P As Decimal?
    Public Property WORKING_L As Decimal?
    Public Property WORKING_R As Decimal?
    Public Property WORKING_S As Decimal?
    Public Property WORKING_B As Decimal?
    Public Property WORKING_K As Decimal?
    Public Property WORKING_J As Decimal?
    Public Property WORKING_TS As Decimal?
    Public Property WORKING_O As Decimal?
    Public Property WORKING_V As Decimal?
    Public Property TOTAL_WORKING As Decimal?
    Public Property WORKING_ADD As Decimal?
    Public Property LATE As Decimal?
    Public Property COMEBACKOUT As Decimal?
    Public Property TOTAL_W_SALARY As Decimal?
    Public Property TOTAL_W_NOSALARY As Decimal?
    Public Property TOTAL_W_H As Decimal?
    Public Property WORKING_MEAL As Decimal?
    Public Property IS_TERMINATE As Boolean?
    Public Property WORK_STATUS As Decimal?
    Public Property TER_LAST_DATE As Date?

    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String

    Public Property WORKING_DA As Decimal?
    Public Property OBJECT_ATTENDANCE As Decimal?
    Public Property OBJECT_ATTENDANCE_NAME As String
    Public Property MIN_OUT_WORK As Decimal?
    Public Property MIN_ON_LEAVE As Decimal?
    Public Property MIN_DEDUCT As Decimal?
    Public Property MIN_LATE As Decimal?
    Public Property MIN_IN_WORK As Decimal?
    Public Property MIN_DEDUCT_WORK As Decimal?
    Public Property MIN_OUT_WORK_DEDUCT As Decimal?
    Public Property MIN_EARLY As Decimal?
    Public Property MIN_LATE_EARLY As Decimal?
    Public Property WORKING_TN As Decimal?
    Public Property WORKING_KLD As Decimal?
    Public Property WORKING_DEDUCT As Decimal?
    Public Property C_AL_T As Decimal?

    Public Property OBJECT_EMPLOYEE_ID As Decimal?

    Public Property OBJECT_EMPLOYEE_ID_KN As Decimal?

    'OT
    Public Property TOTAL_FACTOR1 As Decimal?
    Public Property TOTAL_FACTOR1_5 As Decimal?
    Public Property TOTAL_FACTOR1_8 As Decimal?
    Public Property TOTAL_FACTOR2 As Decimal?
    Public Property TOTAL_FACTOR2_1 As Decimal?
    Public Property TOTAL_FACTOR2_7 As Decimal?
    Public Property TOTAL_FACTOR3 As Decimal?
    Public Property TOTAL_FACTOR3_9 As Decimal?
    Public Property TOTAL_FACTOR As Decimal?

    Public Property OT_DAY As Decimal?
    Public Property OT_NIGHT As Decimal?
    Public Property OT_WEEKEND_DAY As Decimal?
    Public Property OT_WEEKEND_NIGHT As Decimal?
    Public Property OT_HOLIDAY_DAY As Decimal?
    Public Property OT_HOLIDAY_NIGHT As Decimal?
    Public Property TOTAL_NB1 As Decimal?
    Public Property TOTAL_NB1_5 As Decimal?
    Public Property TOTAL_NB1_8 As Decimal?
    Public Property TOTAL_NB2 As Decimal?
    Public Property TOTAL_NB2_1 As Decimal?
    Public Property TOTAL_NB2_7 As Decimal?
    Public Property TOTAL_NB3 As Decimal?
    Public Property TOTAL_NB3_9 As Decimal?
    Public Property NEW_OT_DAY As Decimal?
    Public Property NEW_OT_NIGHT As Decimal?
    Public Property NEW_OT_WEEKEND_DAY As Decimal?
    Public Property NEW_OT_WEEKEND_NIGHT As Decimal?
    Public Property NEW_OT_HOLIDAY_DAY As Decimal?
    Public Property NEW_OT_HOLIDAY_NIGHT As Decimal?
    Public Property NUMBER_FACTOR_CP As Decimal?
    Public Property HOURS_OLD As Decimal?
    Public Property HOURS_NEW As Decimal?
    Public Property WORKING_WFH As Decimal?
    Public Property WORKING_WFH_COM As Decimal?
    Public Property IS_LOCK_NAME As String

    Public Property VIOLATE_TOTAL As Decimal?
    Public Property VIOLATE_DAY As Decimal?
End Class
