Public Class AT_TIME_WORKSTANDARDDTO
    Public Property ID As Decimal
    Public Property YEAR As Decimal
    Public Property CODE1 As String
    Public Property OBJ_EMPLOYEE_ID As Decimal?
    Public Property OBJ_EMPLOYEE_NAME As String
    Public Property OBJ_ATTENDANT_NAME As String
    Public Property OBJ_ATTENDANT_ID As Decimal?
    Public Property WORKSTANDARD_M1 As Decimal?
    Public Property WORKSTANDARD_M2 As Decimal?
    Public Property WORKSTANDARD_M3 As Decimal?
    Public Property WORKSTANDARD_M4 As Decimal?
    Public Property WORKSTANDARD_M5 As Decimal?
    Public Property WORKSTANDARD_M6 As Decimal?
    Public Property WORKSTANDARD_M7 As Decimal?
    Public Property WORKSTANDARD_M8 As Decimal?
    Public Property WORKSTANDARD_M9 As Decimal?
    Public Property WORKSTANDARD_M10 As Decimal?
    Public Property WORKSTANDARD_M11 As Decimal?
    Public Property WORKSTANDARD_M12 As Decimal?
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property IS_EDIT As Decimal?
    Public Property EMPLOYEE_ID As Decimal?
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property EMP_ORG_NAME As String
    Public Property EMP_ORG_DESC As String
    Public Property TITLE_NAME As String
    Public Property IS_EMPLOYEE As Boolean?
    Public Property CONVERSION_FACTOR As Decimal?
    Public Property IS_NOT_CAL_SAT As Boolean?
    Public Property IS_NOT_CAL_SUN As Boolean?
    Public Property IS_NOT_CAL_HALF_SAT As Boolean?
    Public Property IS_NOT_CAL_2_SAT As Boolean?
    Public Property MINUS_MONTHLY_AT As Decimal?
    Public Property DEFAULT_AT As Decimal?

End Class