-- --------------------------------------------------
-- Entity Designer DDL Script for Oracle database
-- --------------------------------------------------
-- Date Created: 4/28/2023 4:35:39 PM
-- Generated from EDMX file: E:\Source\BCG_DEV\CommonDAL\CommonContext.edmx
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'SE_GROUP'
CREATE TABLE "dbo"."SE_GROUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "IS_ADMIN" SMALLINT NULL,
   "CODE" VARCHAR(8000) NOT NULL,
   "EFFECT_DATE" DATETIME NOT NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "IS_HR_ADMIN" SMALLINT NULL,
   "IS_FUNCTION_PERMISSION" DECIMAL(18,0) NULL,
   "IS_ORG_PERMISSION" DECIMAL(18,0) NULL
);

-- Creating table 'SE_FUNCTION'
CREATE TABLE "dbo"."SE_FUNCTION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NULL,
   "MODULE_ID" DECIMAL(18,0) NULL,
   "FID" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "SETUP_SIGNER" DECIMAL(18,0) NULL,
   "ADMIN_HR" DECIMAL(18,0) NULL
);

-- Creating table 'SE_USER'
CREATE TABLE "dbo"."SE_USER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NOT NULL,
   "PASSWORD" NVARCHAR(4000) NULL,
   "FULLNAME" NVARCHAR(4000) NOT NULL,
   "EMAIL" NVARCHAR(4000) NULL,
   "TELEPHONE" NVARCHAR(4000) NULL,
   "LOCATION" NVARCHAR(4000) NULL,
   "IS_APP" SMALLINT NOT NULL,
   "IS_PORTAL" SMALLINT NOT NULL,
   "EMPLOYEE_CODE" VARCHAR(8000) NULL,
   "IS_AD" SMALLINT NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "IS_CHANGE_PASS" SMALLINT NULL,
   "CHANGE_PASS_DATE" DATETIME NULL,
   "REMINDER_COUNT" SMALLINT NULL,
   "MODULE_ADMIN" NVARCHAR(4000) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "EFFECTDATE_TERMINATION" DATETIME NULL,
   "IS_LOGIN" SMALLINT NULL,
   "IS_RC" DECIMAL(18,0) NULL,
   "IS_HR" SMALLINT NULL
);

-- Creating table 'SE_MODULE'
CREATE TABLE "dbo"."SE_MODULE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "MID" NVARCHAR(4000) NOT NULL,
   "NAME_DESC" NVARCHAR(MAX) NULL,
   "IS_ACTIVE" DECIMAL(18,0) NULL,
   "ORDER_BY" DECIMAL(18,0) NULL
);

-- Creating table 'SE_GROUP_PERMISSION'
CREATE TABLE "dbo"."SE_GROUP_PERMISSION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_CREATE" SMALLINT NOT NULL,
   "ALLOW_MODIFY" SMALLINT NOT NULL,
   "ALLOW_DELETE" SMALLINT NOT NULL,
   "ALLOW_PRINT" SMALLINT NOT NULL,
   "ALLOW_IMPORT" SMALLINT NOT NULL,
   "ALLOW_EXPORT" SMALLINT NOT NULL,
   "ALLOW_SPECIAL1" SMALLINT NOT NULL,
   "ALLOW_SPECIAL2" SMALLINT NOT NULL,
   "ALLOW_SPECIAL3" SMALLINT NOT NULL,
   "FUNCTION_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_SPECIAL4" SMALLINT NOT NULL,
   "ALLOW_SPECIAL5" SMALLINT NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'OT_OTHER_LIST'
CREATE TABLE "dbo"."OT_OTHER_LIST" (
   "ID" DECIMAL(18,0) NOT NULL,
   "TYPE_ID" DECIMAL(18,0) NOT NULL,
   "NAME_VN" NVARCHAR(4000) NOT NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "ATTRIBUTE1" NVARCHAR(4000) NULL,
   "ATTRIBUTE2" NVARCHAR(4000) NULL,
   "ATTRIBUTE3" NVARCHAR(4000) NULL,
   "ATTRIBUTE4" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "TYPE_CODE" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ORDERBYID" DECIMAL(18,0) NULL
);

-- Creating table 'OT_OTHER_LIST_GROUP'
CREATE TABLE "dbo"."OT_OTHER_LIST_GROUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL
);

-- Creating table 'OT_OTHER_LIST_TYPE'
CREATE TABLE "dbo"."OT_OTHER_LIST_TYPE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "IS_SYSTEM" SMALLINT NULL
);

-- Creating table 'SE_REPORT'
CREATE TABLE "dbo"."SE_REPORT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "CODE" NVARCHAR(4000) NOT NULL,
   "MODULE_ID" DECIMAL(18,0) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL
);

-- Creating table 'HU_ORGANIZATION'
CREATE TABLE "dbo"."HU_ORGANIZATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NOT NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "DISSOLVE_DATE" DATETIME NULL,
   "FOUNDATION_DATE" DATETIME NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NOT NULL,
   "HIERARCHICAL_PATH" VARCHAR(8000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "FAX" NVARCHAR(4000) NULL,
   "REPRESENTATIVE_ID" DECIMAL(18,0) NULL,
   "ORD_NO" DECIMAL(18,0) NULL,
   "SHORT_NAME" NVARCHAR(MAX) NULL,
   "COST_CENTER_CODE" NVARCHAR(MAX) NULL,
   "UY_BAN" DECIMAL(18,0) NULL
);

-- Creating table 'SE_FUNCTION_GROUP'
CREATE TABLE "dbo"."SE_FUNCTION_GROUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NOT NULL,
   "CODE" NVARCHAR(4000) NULL
);

-- Creating table 'HU_EMPLOYEE'
CREATE TABLE "dbo"."HU_EMPLOYEE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_CODE" NVARCHAR(4000) NULL,
   "FIRST_NAME_VN" NVARCHAR(4000) NULL,
   "LAST_NAME_VN" NVARCHAR(4000) NULL,
   "FULLNAME_VN" NVARCHAR(4000) NULL,
   "FIRST_NAME_EN" VARCHAR(8000) NULL,
   "LAST_NAME_EN" NVARCHAR(4000) NULL,
   "FULLNAME_EN" NVARCHAR(4000) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "WORK_STATUS" DECIMAL(18,0) NULL,
   "CONTRACT_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "JOIN_DATE" DATETIME NULL,
   "DIRECT_MANAGER" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "LAST_WORKING_ID" DECIMAL(18,0) NULL,
   "TER_EFFECT_DATE" DATETIME NULL,
   "TER_LAST_DATE" DATETIME NULL,
   "STAFF_RANK_ID" DECIMAL(18,0) NULL,
   "ITIME_ID" NVARCHAR(MAX) NULL,
   "PA_OBJECT_SALARY_ID" DECIMAL(18,0) NULL,
   "IS_3B" SMALLINT NULL,
   "EMP_STATUS" DECIMAL(18,0) NULL,
   "IS_KIEM_NHIEM" DECIMAL(18,0) NULL,
   "OBJECT_LABOR" DECIMAL(18,0) NULL,
   "OBJECTTIMEKEEPING" DECIMAL(18,0) NULL,
   "OBJECT_EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "WORK_PLACE_ID" DECIMAL(18,0) NULL,
   "OBJECT_ATTENDANT_ID" DECIMAL(18,0) NULL,
   "MATHE" DECIMAL(18,0) NULL,
   "THETU" NVARCHAR(MAX) NULL,
   "DM_ID" DECIMAL(18,0) NULL,
   "IDM_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HU_TERMINATE'
CREATE TABLE "dbo"."HU_TERMINATE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "IS_NOHIRE" SMALLINT NULL,
   "SEND_DATE" DATETIME NULL,
   "TER_REASON_DETAIL" NVARCHAR(4000) NULL,
   "LAST_DATE" DATETIME NULL,
   "STATUS_ID" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "EMP_SENIORITY" NVARCHAR(4000) NULL,
   "LAST_WORKING_ID" DECIMAL(18,0) NULL,
   "APPROVAL_DATE" DATETIME NULL,
   "IDENTIFI_CARD" DECIMAL(18,0) NULL,
   "IDENTIFI_RDATE" DATETIME NULL,
   "IDENTIFI_STATUS" NVARCHAR(4000) NULL,
   "SUN_CARD" DECIMAL(18,0) NULL,
   "SUN_RDATE" DATETIME NULL,
   "SUN_STATUS" NVARCHAR(4000) NULL,
   "INSURANCE_CARD" DECIMAL(18,0) NULL,
   "INSURANCE_RDATE" DATETIME NULL,
   "INSURANCE_STATUS" NVARCHAR(4000) NULL,
   "REMAINING_LEAVE" DECIMAL(18,0) NULL,
   "PAYMENT_LEAVE" DECIMAL(18,0) NULL,
   "AMOUNT_VIOLATIONS" DECIMAL(18,0) NULL,
   "AMOUNT_WRONGFUL" DECIMAL(18,0) NULL,
   "ALLOWANCE_TERMINATE" DECIMAL(18,0) NULL,
   "TRAINING_COSTS" DECIMAL(18,0) NULL,
   "OTHER_COMPENSATION" DECIMAL(18,0) NULL,
   "COMPENSATORY_LEAVE" DECIMAL(18,0) NULL,
   "COMPENSATORY_PAYMENT" DECIMAL(18,0) NULL,
   "DECISION_NO" NVARCHAR(4000) NULL,
   "SIGN_DATE" DATETIME NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "SIGN_NAME" NVARCHAR(4000) NULL,
   "SIGN_TITLE" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "IDENTIFI_MONEY" DECIMAL(18,0) NULL,
   "SUN_MONEY" DECIMAL(18,0) NULL,
   "INSURANCE_MONEY" DECIMAL(18,0) NULL,
   "IS_3B" SMALLINT NULL
);

-- Creating table 'SE_MAIL'
CREATE TABLE "dbo"."SE_MAIL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "SUBJECT" NVARCHAR(4000) NULL,
   "MAIL_FROM" NVARCHAR(4000) NULL,
   "MAIL_TO" NVARCHAR(4000) NULL,
   "MAIL_CC" NVARCHAR(4000) NULL,
   "MAIL_BCC" NVARCHAR(4000) NULL,
   "CONTENT" NVARCHAR(MAX) NULL,
   "VIEW_NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "ATTACHMENT" NVARCHAR(MAX) NULL,
   "CREATE_BY" NVARCHAR(MAX) NULL,
   "CREATE_DATE" DATETIME NULL,
   "SEND_DATE" DATETIME NULL,
   "RUN_ROW" DECIMAL(18,0) NULL,
   "ORDER_BY" DECIMAL(18,0) NULL,
   "WAITING" DECIMAL(18,0) NULL
);

-- Creating table 'SE_REMINDER'
CREATE TABLE "dbo"."SE_REMINDER" (
   "USERNAME" NVARCHAR(4000) NOT NULL,
   "TYPE" SMALLINT NOT NULL,
   "VALUE" NVARCHAR(4000) NULL,
   "ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_APP_PROCESS'
CREATE TABLE "dbo"."SE_APP_PROCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NULL,
   "ACTFLG" VARCHAR(8000) NULL,
   "PROCESS_CODE" VARCHAR(8000) NULL,
   "NUMREQUEST" DECIMAL(18,0) NULL,
   "EMAIL" NVARCHAR(4000) NULL
);

-- Creating table 'SE_APP_SETUP'
CREATE TABLE "dbo"."SE_APP_SETUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "PROCESS_ID" DECIMAL(18,0) NULL,
   "TEMPLATE_ID" DECIMAL(18,0) NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "FROM_DATE" DATETIME NULL,
   "TO_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "FROM_HOUR" DECIMAL(18,0) NULL,
   "TO_HOUR" DECIMAL(18,0) NULL,
   "FROM_DAY" DECIMAL(18,0) NULL,
   "TO_DAY" DECIMAL(18,0) NULL,
   "MAIL_ACCEPTED" NVARCHAR(MAX) NULL,
   "MAIL_ACCEPTING" NVARCHAR(MAX) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "SIGN_ID" DECIMAL(18,0) NULL,
   "LEAVEPLAN_ID" DECIMAL(18,0) NULL,
   "IS_IGNORE_APPROVE_LEVEL" DECIMAL(18,0) NULL,
   "GROUP_TITLE_ID" DECIMAL(18,0) NULL,
   "IS_OVER_LIMIT" DECIMAL(18,0) NULL
);

-- Creating table 'SE_APP_SETUPEXT'
CREATE TABLE "dbo"."SE_APP_SETUPEXT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "SUB_EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "PROCESS_ID" DECIMAL(18,0) NULL,
   "FROM_DATE" DATETIME NULL,
   "TO_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REPLACEALL" DECIMAL(18,0) NULL
);

-- Creating table 'SE_APP_TEMPLATE'
CREATE TABLE "dbo"."SE_APP_TEMPLATE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "TEMPLATE_NAME" NVARCHAR(4000) NULL,
   "TEMPLATE_TYPE" DECIMAL(18,0) NULL,
   "TEMPLATE_ORDER" DECIMAL(18,0) NULL,
   "ACTFLG" VARCHAR(8000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "TEMPLATE_CODE" NVARCHAR(MAX) NULL
);

-- Creating table 'SE_APP_TEMPLATE_DTL'
CREATE TABLE "dbo"."SE_APP_TEMPLATE_DTL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "TEMPLATE_ID" DECIMAL(18,0) NULL,
   "APP_LEVEL" DECIMAL(18,0) NULL,
   "APP_TYPE" DECIMAL(18,0) NULL,
   "APP_ID" DECIMAL(18,0) NULL,
   "INFORM_DATE" DECIMAL(18,0) NULL,
   "INFORM_EMAIL" VARCHAR(8000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_WORKING'
CREATE TABLE "dbo"."HU_WORKING" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TITLE_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "TRANSFER_TYPE" DECIMAL(18,0) NULL,
   "TRANSFER_REASON" DECIMAL(18,0) NULL,
   "INDIRECT_MANAGER" DECIMAL(18,0) NULL,
   "DIRECT_MANAGER" DECIMAL(18,0) NULL,
   "IS_DECISION" SMALLINT NULL,
   "DECISION_ID" DECIMAL(18,0) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_DATE" DATETIME NULL,
   "WORKING_TYPE" SMALLINT NULL,
   "COST_CENTER" DECIMAL(18,0) NULL,
   "BASIC_SAL" DECIMAL(18,0) NULL,
   "SOFT_SAL" DECIMAL(18,0) NULL,
   "OTHER_SAL" DECIMAL(18,0) NULL,
   "COEFFICIENT" DECIMAL(18,0) NULL,
   "CONTRACTUAL_SAL" DECIMAL(18,0) NULL,
   "SALARY_ENTERPRISE_ID" DECIMAL(18,0) NULL,
   "ALLOWANCE_IDS" NVARCHAR(4000) NULL,
   "ALLOWANCE_SAL" DECIMAL(18,0) NULL,
   "ALLOWANCE_TOTAL" DECIMAL(18,0) NULL
);

-- Creating table 'SE_CHOSEN_ORG'
CREATE TABLE "dbo"."SE_CHOSEN_ORG" (
   "ORG_ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NOT NULL
);

-- Creating table 'HU_EMPLOYEE_CV'
CREATE TABLE "dbo"."HU_EMPLOYEE_CV" (
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "GENDER" DECIMAL(18,0) NULL,
   "IMAGE" NVARCHAR(4000) NULL,
   "BIRTH_DATE" DATETIME NULL,
   "BIRTH_PLACE" DECIMAL(18,0) NULL,
   "MARITAL_STATUS" DECIMAL(18,0) NULL,
   "RELIGION" DECIMAL(18,0) NULL,
   "NATIVE" DECIMAL(18,0) NULL,
   "NATIONALITY" DECIMAL(18,0) NULL,
   "PER_ADDRESS" NVARCHAR(4000) NULL,
   "PER_PROVINCE" DECIMAL(18,0) NULL,
   "HOME_PHONE" NVARCHAR(4000) NULL,
   "MOBILE_PHONE" NVARCHAR(4000) NULL,
   "ID_NO" NVARCHAR(4000) NULL,
   "ID_DATE" DATETIME NULL,
   "PASS_NO" NVARCHAR(4000) NULL,
   "PASS_DATE" DATETIME NULL,
   "PASS_EXPIRE" DATETIME NULL,
   "PASS_PLACE" NVARCHAR(4000) NULL,
   "VISA" NVARCHAR(4000) NULL,
   "VISA_DATE" DATETIME NULL,
   "VISA_EXPIRE" DATETIME NULL,
   "VISA_PLACE" NVARCHAR(4000) NULL,
   "WORK_PERMIT" NVARCHAR(4000) NULL,
   "WORK_PERMIT_DATE" DATETIME NULL,
   "WORK_PERMIT_EXPIRE" DATETIME NULL,
   "WORK_EMAIL" NVARCHAR(4000) NULL,
   "NAV_ADDRESS" NVARCHAR(4000) NULL,
   "NAV_PROVINCE" DECIMAL(18,0) NULL,
   "PIT_CODE" VARCHAR(8000) NULL,
   "PER_EMAIL" NVARCHAR(4000) NULL,
   "CONTACT_PER" NVARCHAR(4000) NULL,
   "CONTACT_PER_PHONE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ID_PLACE" DECIMAL(18,0) NULL,
   "WORK_PERMIT_PLACE" NVARCHAR(4000) NULL,
   "BANK_ID" DECIMAL(18,0) NULL,
   "BANK_BRANCH_ID" DECIMAL(18,0) NULL,
   "NGAY_VAO_DOAN" DATETIME NULL,
   "NOI_VAO_DOAN" NVARCHAR(4000) NULL,
   "CHUC_VU_DOAN" NVARCHAR(4000) NULL,
   "DOAN_PHI" SMALLINT NULL,
   "NGAY_VAO_DANG" DATETIME NULL,
   "NOI_VAO_DANG" NVARCHAR(4000) NULL,
   "CHUC_VU_DANG" NVARCHAR(4000) NULL,
   "DANG_PHI" SMALLINT NULL,
   "BANK_NO" NVARCHAR(4000) NULL,
   "CAREER" NVARCHAR(4000) NULL
);

-- Creating table 'HU_STAFF_RANK'
CREATE TABLE "dbo"."HU_STAFF_RANK" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_LDAP'
CREATE TABLE "dbo"."SE_LDAP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "LDAP_NAME" NVARCHAR(4000) NOT NULL,
   "DOMAIN_NAME" NVARCHAR(4000) NOT NULL,
   "BASE_DN" NVARCHAR(4000) NOT NULL
);

-- Creating table 'SE_USER_ORG_ACCESS'
CREATE TABLE "dbo"."SE_USER_ORG_ACCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USER_ID" DECIMAL(18,0) NOT NULL,
   "ORG_ID" DECIMAL(18,0) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL
);

-- Creating table 'SE_USER_PERMISSION'
CREATE TABLE "dbo"."SE_USER_PERMISSION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USER_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_CREATE" SMALLINT NOT NULL,
   "ALLOW_MODIFY" SMALLINT NOT NULL,
   "ALLOW_DELETE" SMALLINT NOT NULL,
   "ALLOW_PRINT" SMALLINT NOT NULL,
   "ALLOW_IMPORT" SMALLINT NOT NULL,
   "ALLOW_EXPORT" SMALLINT NOT NULL,
   "ALLOW_SPECIAL1" SMALLINT NOT NULL,
   "ALLOW_SPECIAL2" SMALLINT NOT NULL,
   "ALLOW_SPECIAL3" SMALLINT NOT NULL,
   "FUNCTION_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_SPECIAL4" SMALLINT NOT NULL,
   "ALLOW_SPECIAL5" SMALLINT NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HUV_SE_GRP_SE_USR'
CREATE TABLE "dbo"."HUV_SE_GRP_SE_USR" (
   "SE_USERS_ID" DECIMAL(18,0) NOT NULL,
   "SE_GROUPS_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_VIEW_CONFIG'
CREATE TABLE "dbo"."SE_VIEW_CONFIG" (
   "CODE_NAME" NVARCHAR(MAX) NOT NULL,
   "CONFIG_DATA" NVARCHAR(MAX) NULL
);

-- Creating table 'AT_TIME_MANUAL'
CREATE TABLE "dbo"."AT_TIME_MANUAL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "MORNING_ID" DECIMAL(18,0) NULL,
   "AFTERNOON_ID" DECIMAL(18,0) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "IS_PAID_RICE" DECIMAL(18,0) NULL,
   "LIMIT_DAY" DECIMAL(18,0) NULL,
   "LIMIT_YEAR" DECIMAL(18,0) NULL
);

-- Creating table 'SE_CASE_CONFIG'
CREATE TABLE "dbo"."SE_CASE_CONFIG" (
   "CODE_NAME" NVARCHAR(MAX) NOT NULL,
   "CODE_CASE" NVARCHAR(MAX) NOT NULL,
   "DESCRIPTIONS" NVARCHAR(MAX) NULL,
   "STATUS" DECIMAL(18,0) NULL
);

-- Creating table 'HU_SIGNER'
CREATE TABLE "dbo"."HU_SIGNER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME" NVARCHAR(4000) NULL,
   "LEVEL_NAME" NVARCHAR(4000) NULL,
   "TITLE_NAME" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(MAX) NULL,
   "ACTFLG" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(MAX) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(MAX) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(MAX) NULL,
   "SIGNER_CODE" NVARCHAR(MAX) NOT NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "SIGNER_ID" DECIMAL(18,0) NULL
);

-- Creating table 'SE_MAIL_TEMPLATE'
CREATE TABLE "dbo"."SE_MAIL_TEMPLATE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "TITLE" NVARCHAR(MAX) NULL,
   "CONTENT" NVARCHAR(MAX) NULL,
   "NAME" NVARCHAR(MAX) NULL,
   "MAIL_CC" NVARCHAR(MAX) NULL,
   "REMARK" NVARCHAR(MAX) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "GROUP_MAIL" NVARCHAR(MAX) NULL,
   "IS_MAIL_CC" DECIMAL(18,0) NULL
);

-- Creating table 'HU_NATION'
CREATE TABLE "dbo"."HU_NATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_GROUP_ORG_ACCESS'
CREATE TABLE "dbo"."SE_GROUP_ORG_ACCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_GROUP_ORG_FUN_ACCESS'
CREATE TABLE "dbo"."SE_GROUP_ORG_FUN_ACCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'HUV_ORGANIZATION'
CREATE TABLE "dbo"."HUV_ORGANIZATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ORG_NAME" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "COST_CENTER_CODE" NVARCHAR(4000) NULL,
   "PROVINCE_NAME" NVARCHAR(4000) NULL,
   "PIT_NO" NVARCHAR(4000) NULL,
   "NUMBER_BUSINESS" NVARCHAR(4000) NULL,
   "DATE_BUSINESS" DATETIME NULL,
   "ORG_NAME1" NVARCHAR(4000) NULL,
   "ORG_NAME2" NVARCHAR(4000) NULL,
   "ORG_NAME3" NVARCHAR(4000) NULL,
   "ORG_NAME4" NVARCHAR(4000) NULL,
   "ORG_NAME5" NVARCHAR(4000) NULL,
   "ORG_NAME6" NVARCHAR(4000) NULL,
   "ORG_NAME7" NVARCHAR(4000) NULL,
   "ORG_NAME8" NVARCHAR(4000) NULL,
   "ORG_NAME9" NVARCHAR(4000) NULL,
   "ORG_ID1" DECIMAL(18,0) NULL,
   "ORG_ID2" DECIMAL(18,0) NULL,
   "ORG_ID3" DECIMAL(18,0) NULL,
   "ORG_ID4" DECIMAL(18,0) NULL,
   "ORG_ID5" DECIMAL(18,0) NULL,
   "ORG_ID6" DECIMAL(18,0) NULL,
   "ORG_ID7" DECIMAL(18,0) NULL,
   "ORG_ID8" DECIMAL(18,0) NULL,
   "ORG_ID9" DECIMAL(18,0) NULL,
   "ORG_CODE1" NVARCHAR(4000) NULL,
   "ORG_CODE2" NVARCHAR(4000) NULL,
   "ORG_CODE3" NVARCHAR(4000) NULL,
   "ORG_CODE4" NVARCHAR(4000) NULL,
   "ORG_CODE5" NVARCHAR(4000) NULL,
   "ORG_CODE6" NVARCHAR(4000) NULL,
   "ORG_CODE7" NVARCHAR(4000) NULL,
   "ORG_CODE8" NVARCHAR(4000) NULL,
   "ORG_CODE9" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER1" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER2" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER3" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER4" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER5" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER6" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER7" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER8" NVARCHAR(4000) NULL,
   "ORG_COST_CENTER9" NVARCHAR(4000) NULL,
   "ORD_NO1" VARCHAR(8000) NULL,
   "ORD_NO2" VARCHAR(8000) NULL,
   "ORD_NO3" VARCHAR(8000) NULL,
   "ORD_NO4" VARCHAR(8000) NULL,
   "ORD_NO5" VARCHAR(8000) NULL,
   "ORD_NO6" VARCHAR(8000) NULL,
   "ORD_NO7" VARCHAR(8000) NULL,
   "ORD_NO8" VARCHAR(8000) NULL,
   "ORD_NO9" VARCHAR(8000) NULL,
   "ORG_PATH" NVARCHAR(4000) NULL,
   "ORD_NO" DECIMAL(18,0) NULL,
   "DISSOLVE_DATE" DATETIME NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "HIERARCHICAL_PATH" NVARCHAR(MAX) NULL
);

-- Creating table 'HU_WORK_PLACE'
CREATE TABLE "dbo"."HU_WORK_PLACE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "PLACE" NVARCHAR(4000) NULL,
   "PROVINCE_ID" DECIMAL(18,0) NULL,
   "DISTRICT_ID" DECIMAL(18,0) NULL,
   "WARD_ID" DECIMAL(18,0) NULL,
   "REGION_ID" DECIMAL(18,0) NULL,
   "PHONE_NUMBER" NVARCHAR(4000) NULL,
   "FAX" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_REGISTER_USER'
CREATE TABLE "dbo"."SE_REGISTER_USER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "APP_USER" DECIMAL(18,0) NULL,
   "PORTAL_USER" DECIMAL(18,0) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL
);

-- Creating table 'SE_GRP_SE_USR1'
CREATE TABLE "dbo"."SE_GRP_SE_USR1" (
   "SE_GROUPS_ID" DECIMAL(18,0) NOT NULL,
   "SE_USERS_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_USER_PERMISSION_ORG'
CREATE TABLE "dbo"."SE_USER_PERMISSION_ORG" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USER_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_CREATE" SMALLINT NOT NULL,
   "ALLOW_MODIFY" SMALLINT NOT NULL,
   "ALLOW_DELETE" SMALLINT NOT NULL,
   "ALLOW_PRINT" SMALLINT NOT NULL,
   "ALLOW_IMPORT" SMALLINT NOT NULL,
   "ALLOW_EXPORT" SMALLINT NOT NULL,
   "ALLOW_SPECIAL1" SMALLINT NOT NULL,
   "ALLOW_SPECIAL2" SMALLINT NOT NULL,
   "ALLOW_SPECIAL3" SMALLINT NOT NULL,
   "FUNCTION_ID" DECIMAL(18,0) NOT NULL,
   "ALLOW_SPECIAL4" SMALLINT NOT NULL,
   "ALLOW_SPECIAL5" SMALLINT NOT NULL,
   "CREATED_DATE" DATETIME NOT NULL,
   "CREATED_BY" NVARCHAR(4000) NOT NULL,
   "CREATED_LOG" NVARCHAR(4000) NOT NULL,
   "MODIFIED_DATE" DATETIME NOT NULL,
   "MODIFIED_BY" NVARCHAR(4000) NOT NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NOT NULL,
   "GROUP_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "LOCATION_ID" DECIMAL(18,0) NULL
);

-- Creating table 'SE_SYSTEM_MAINTAIN'
CREATE TABLE "dbo"."SE_SYSTEM_MAINTAIN" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CONTRACT_MAINTAIN" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXPIRE_TDATE" DATETIME NULL,
   "SIGN_DATE" DATETIME NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'TR_REQUEST'
CREATE TABLE "dbo"."TR_REQUEST" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "REQUEST_DATE" DATETIME NULL,
   "YEAR" DECIMAL(18,0) NULL,
   "TR_PLAN_ID" DECIMAL(18,0) NULL,
   "CONTENT" NVARCHAR(4000) NULL,
   "EXPECTED_DATE" DATETIME NULL,
   "START_DATE" DATETIME NULL,
   "EXPECTED_COST" DECIMAL(18,0) NULL,
   "TR_CURRENCY_ID" DECIMAL(18,0) NULL,
   "STATUS_ID" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REQUEST_SENDER_ID" DECIMAL(18,0) NULL,
   "IS_IRREGULARLY" DECIMAL(18,0) NULL,
   "TR_COURSE_ID" DECIMAL(18,0) NULL,
   "TRAIN_FORM_ID" DECIMAL(18,0) NULL,
   "PROPERTIES_NEED_ID" DECIMAL(18,0) NULL,
   "TR_UNIT_ID" DECIMAL(18,0) NULL,
   "TARGET_TRAIN" NVARCHAR(4000) NULL,
   "VENUE" NVARCHAR(4000) NULL,
   "ATTACH_FILE" NVARCHAR(4000) NULL,
   "REJECT_REASON" NVARCHAR(4000) NULL,
   "EXPECT_DATE_TO" DATETIME NULL,
   "SENDER_TITLE_ID" DECIMAL(18,0) NULL,
   "OTHER_COURSE" NVARCHAR(4000) NULL,
   "TRAINER_NUMBER" DECIMAL(18,0) NULL,
   "TR_COMMIT" DECIMAL(18,0) NULL,
   "CERTIFICATE" DECIMAL(18,0) NULL,
   "TR_PLACE" NVARCHAR(4000) NULL,
   "TEACHERS_ID" NVARCHAR(4000) NULL,
   "CENTERS_ID" NVARCHAR(4000) NULL,
   "REQUEST_CODE" NVARCHAR(MAX) NULL
);

-- Creating table 'TR_COURSE'
CREATE TABLE "dbo"."TR_COURSE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "TR_CERTIFICATE_ID" DECIMAL(18,0) NULL,
   "ACTFLG" SMALLINT NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "TR_CER_GROUP_ID" DECIMAL(18,0) NULL,
   "TR_TRAIN_FIELD" DECIMAL(18,0) NULL,
   "TR_PROGRAM_GROUP" DECIMAL(18,0) NULL,
   "DRIVER" SMALLINT NULL,
   "REMARK" NVARCHAR(4000) NULL
);

-- Creating table 'SE_BACKGROUND_PORTAL'
CREATE TABLE "dbo"."SE_BACKGROUND_PORTAL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "FROM_DATE" NVARCHAR(4000) NULL,
   "TO_DATE" NVARCHAR(4000) NULL,
   "NOTE" NVARCHAR(4000) NULL,
   "BACKGROUND" NVARCHAR(4000) NULL,
   "FILEPATH" NVARCHAR(MAX) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_TITLE_BLD'
CREATE TABLE "dbo"."HU_TITLE_BLD" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL
);

-- Creating table 'PA_FRAME_PRODUCTIVITY'
CREATE TABLE "dbo"."PA_FRAME_PRODUCTIVITY" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "SHORT_NAME" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "HIERARCHICAL_PATH" VARCHAR(8000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "COEFFICIENT" DECIMAL(18,0) NULL,
   "IS_LEVEL1" DECIMAL(18,0) NULL,
   "IS_LEVEL2" DECIMAL(18,0) NULL,
   "IS_LEVEL3" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'PA_FRAME_SALARY'
CREATE TABLE "dbo"."PA_FRAME_SALARY" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "HIERARCHICAL_PATH" VARCHAR(8000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "COEFFICIENT" DECIMAL(18,0) NULL,
   "PROMOTE_MONTH" DECIMAL(18,0) NULL,
   "NEXT_CODE" NVARCHAR(4000) NULL,
   "IS_LEVEL1" DECIMAL(18,0) NULL,
   "IS_LEVEL2" DECIMAL(18,0) NULL,
   "IS_LEVEL3" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'HU_ORGANIZATION_OM'
CREATE TABLE "dbo"."HU_ORGANIZATION_OM" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "LEVEL_ID" DECIMAL(18,0) NULL,
   "DISSOLVE_DATE" DATETIME NULL,
   "FOUNDATION_DATE" DATETIME NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "HIERARCHICAL_PATH" VARCHAR(8000) NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "ADDRESS" NVARCHAR(4000) NULL,
   "FAX" NVARCHAR(4000) NULL,
   "REPRESENTATIVE_ID" DECIMAL(18,0) NULL,
   "MOBILE" NVARCHAR(4000) NULL,
   "PROVINCE_NAME" NVARCHAR(4000) NULL,
   "COST_CENTER_CODE" NVARCHAR(4000) NULL,
   "ORD_NO" DECIMAL(18,0) NULL,
   "NUMBER_BUSINESS" NVARCHAR(4000) NULL,
   "DATE_BUSINESS" DATETIME NULL,
   "PIT_NO" NVARCHAR(4000) NULL,
   "HU_ORG_TITLEID" DECIMAL(18,0) NULL,
   "NLEVEL" BIGINT NULL,
   "GROUPPROJECT" DECIMAL(18,0) NULL,
   "EFFECTDATE" DATETIME NULL,
   "STATUS_ID" DECIMAL(18,0) NULL
);

-- Creating table 'PE_WORK_EMPLOYEE'
CREATE TABLE "dbo"."PE_WORK_EMPLOYEE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "PROCESS_ID" DECIMAL(18,0) NULL,
   "WORK_NAME" NVARCHAR(4000) NULL,
   "RESULT" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'PE_WORK_MANAGER'
CREATE TABLE "dbo"."PE_WORK_MANAGER" (
   "ID" DECIMAL(18,0) NOT NULL,
   "WORK_ID" DECIMAL(18,0) NULL,
   "WORK_NAME" NVARCHAR(4000) NULL,
   "RESULT" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "PROCESS_ID" DECIMAL(18,0) NULL
);

-- Creating table 'PE_WORK_MANAGER_CONCLUDE'
CREATE TABLE "dbo"."PE_WORK_MANAGER_CONCLUDE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "PROCESS_ID" DECIMAL(18,0) NULL,
   "CONCLUDE_TYPE" DECIMAL(18,0) NULL,
   "DATE_PROBATION" DATETIME NULL,
   "CONTRACT_TYPE" DECIMAL(18,0) NULL,
   "APOINT_TITLE" DECIMAL(18,0) NULL,
   "APOINT_OTHER" NVARCHAR(4000) NULL,
   "MOVE_TITLE" DECIMAL(18,0) NULL,
   "MOVE_OTHER" NVARCHAR(4000) NULL,
   "IS_SAL_CHANGE" DECIMAL(18,0) NULL,
   "SAL_SUGGET" DECIMAL(18,0) NULL,
   "IS_CHANGE_TITLE" DECIMAL(18,0) NULL,
   "CHANGE_TITLE" DECIMAL(18,0) NULL,
   "CHANGE_OTHER" NVARCHAR(4000) NULL,
   "STAFF_RANK" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "IS_CONFIRM" DECIMAL(18,0) NULL,
   "NOTE" NVARCHAR(MAX) NULL,
   "IS_JOBBAND_CHANGE" DECIMAL(18,0) NULL
);

-- Creating table 'HU_JOB_BAND'
CREATE TABLE "dbo"."HU_JOB_BAND" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "LEVEL_FROM" VARCHAR(8000) NULL,
   "LEVEL_TO" VARCHAR(8000) NULL,
   "STATUS" SMALLINT NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" VARCHAR(8000) NULL,
   "CREATED_LOG" VARCHAR(8000) NULL,
   "MODIFIED_BY" VARCHAR(8000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_LOG" VARCHAR(8000) NULL,
   "TITLE_GROUP_ID" DECIMAL(18,0) NULL
);

-- Creating table 'HUV_ORGANIZATION_CHILD'
CREATE TABLE "dbo"."HUV_ORGANIZATION_CHILD" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "ORG_NAME" NVARCHAR(4000) NULL,
   "STATUS" NVARCHAR(4000) NULL,
   "DISSOLVE_DATE" DATETIME NULL,
   "DESCRIPTION_PATH" NVARCHAR(4000) NULL,
   "ORDER_BY" VARCHAR(8000) NULL,
   "CHILD_COUNT" DECIMAL(18,0) NULL,
   "HIERARCHICAL_PATH" NVARCHAR(MAX) NULL,
   "ORD_NO" DECIMAL(18,0) NULL
);

-- Creating table 'PROCESS_APPROVED_STATUS'
CREATE TABLE "dbo"."PROCESS_APPROVED_STATUS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "EMPLOYEE_APPROVED" DECIMAL(18,0) NULL,
   "APP_DATE" DATETIME NULL,
   "APP_LEVEL" DECIMAL(18,0) NULL,
   "APP_NOTES" NVARCHAR(4000) NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "APP_STATUS" DECIMAL(18,0) NULL,
   "PE_PERIOD_ID" DECIMAL(18,0) NULL,
   "ID_REGGROUP" DECIMAL(18,0) NULL,
   "TEMPLATE_ID" DECIMAL(18,0) NULL,
   "PROCESS_TYPE" NVARCHAR(4000) NULL,
   "TOKEN" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "EXP_DATE" DATETIME NULL,
   "MODIFIED_BY" DECIMAL(18,0) NULL
);

-- Creating table 'HU_TITLE'
CREATE TABLE "dbo"."HU_TITLE" (
   "ID" DECIMAL(18,0) NOT NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME_EN" NVARCHAR(4000) NULL,
   "NAME_VN" NVARCHAR(4000) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "TITLE_GROUP_ID" DECIMAL(18,0) NULL,
   "STATUS" SMALLINT NULL,
   "LIST_PC_ID" DECIMAL(18,0) NULL,
   "DRIVE_INFOR" DECIMAL(18,0) NULL,
   "WORK_INVOLVE_ID" DECIMAL(18,0) NULL,
   "OVT" DECIMAL(18,0) NULL,
   "UPLOAD_FILE" NVARCHAR(4000) NULL,
   "LEVEL_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "CSM_1" DECIMAL(18,0) NULL,
   "JOB_ID" DECIMAL(18,0) NULL,
   "LM" DECIMAL(18,0) NULL,
   "ISOWNER" SMALLINT NULL,
   "CSM" DECIMAL(18,0) NULL,
   "IS_NONPHYSICAL" SMALLINT NULL,
   "COST_CENTER" NVARCHAR(4000) NULL,
   "JOB_SPEC" NVARCHAR(4000) NULL,
   "MASTER" DECIMAL(18,0) NULL,
   "CONCURRENT" SMALLINT NULL,
   "HIRING_STATUS" SMALLINT NULL,
   "IS_PLAN" SMALLINT NULL,
   "INTERIM" DECIMAL(18,0) NULL,
   "WORK_LOCATION" DECIMAL(18,0) NULL,
   "CSM_2" DECIMAL(18,0) NULL,
   "CSM_3" DECIMAL(18,0) NULL,
   "CSM_4" DECIMAL(18,0) NULL,
   "ISAUTOCSM" SMALLINT NULL,
   "NAME_SUM" NVARCHAR(4000) NULL,
   "GROUP_EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "IS_CBCD" DECIMAL(18,0) NULL,
   "CHUCVU_ID" DECIMAL(18,0) NULL,
   "TITLE_BLD_ID" DECIMAL(18,0) NULL,
   "TITLE_TBL_ID" DECIMAL(18,0) NULL,
   "IS_PERCENT" DECIMAL(18,0) NULL,
   "CV_COEF" DECIMAL(18,0) NULL,
   "TN_COEF" DECIMAL(18,0) NULL,
   "EFFECTIVE_DATE" DATETIME NULL,
   "TYPE_ACTIVITIES" NVARCHAR(4000) NULL,
   "FILENAME" NVARCHAR(4000) NULL,
   "UPLOADFILE" NVARCHAR(4000) NULL,
   "WORKING_TIME" DECIMAL(18,0) NULL
);

-- Creating table 'HU_SIGNER_SETUP'
CREATE TABLE "dbo"."HU_SIGNER_SETUP" (
   "ID" DECIMAL(18,0) NOT NULL,
   "FUNC_ID" DECIMAL(18,0) NULL,
   "SIGNER_ID" DECIMAL(18,0) NULL,
   "SETUP_TYPE" DECIMAL(18,0) NULL,
   "REMARK" NVARCHAR(4000) NULL,
   "ACTFLG" NVARCHAR(4000) NULL,
   "EFFECT_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "BASE_AUTHOR" NVARCHAR(4000) NULL,
   "AUTHOR_EFFECT_DATE" DATETIME NULL,
   "DEPUTY_AUTHOR" NVARCHAR(4000) NULL,
   "CER_BUS_RESG" NVARCHAR(4000) NULL,
   "CER_BUS_RESG_EFFECT_DATE" DATETIME NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "SIGNER_TITLE" NVARCHAR(4000) NULL,
   "BASE1" NVARCHAR(4000) NULL,
   "BASE2" NVARCHAR(4000) NULL,
   "BASE3" NVARCHAR(4000) NULL,
   "BASE4" NVARCHAR(4000) NULL,
   "BASE5" NVARCHAR(4000) NULL,
   "BASE6" NVARCHAR(4000) NULL
);

-- Creating table 'HU_FOLDERS'
CREATE TABLE "dbo"."HU_FOLDERS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "FOLDER_NAME" NVARCHAR(4000) NULL,
   "LINK" NVARCHAR(4000) NULL,
   "PARENT_ID" DECIMAL(18,0) NULL
);

-- Creating table 'SE_USER_PERMISSION_ORG_DETAIL'
CREATE TABLE "dbo"."SE_USER_PERMISSION_ORG_DETAIL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USER_ID" DECIMAL(18,0) NULL,
   "FUNCTION_ID" DECIMAL(18,0) NULL,
   "ORG_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'SE_USER_PERMISSION_ORG_WL'
CREATE TABLE "dbo"."SE_USER_PERMISSION_ORG_WL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USER_ID" DECIMAL(18,0) NULL,
   "FUNCTION_ID" DECIMAL(18,0) NULL,
   "WL_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL
);

-- Creating table 'PO_EVENT_SEND_MAIL'
CREATE TABLE "dbo"."PO_EVENT_SEND_MAIL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EVENT_ID" DECIMAL(18,0) NULL,
   "ACTION_DATE" DATETIME NULL,
   "ACTION_STATUS" DECIMAL(18,0) NULL,
   "RUN_START" DATETIME NULL,
   "RUN_END" DATETIME NULL
);

-- Creating table 'PO_EVENT'
CREATE TABLE "dbo"."PO_EVENT" (
   "ID" DECIMAL(18,0) NOT NULL,
   "TITLE" NVARCHAR(4000) NULL,
   "DETAIL" NVARCHAR(MAX) NULL,
   "ADD_TIME" DATETIME NULL,
   "IS_SHOW" SMALLINT NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "START_DATE" DATETIME NULL,
   "END_DATE" DATETIME NULL,
   "ATTACH_FILE" NVARCHAR(4000) NULL,
   "FILENAME" NVARCHAR(4000) NULL
);

-- Creating table 'PO_EVENT_EMP'
CREATE TABLE "dbo"."PO_EVENT_EMP" (
   "PO_EVENT_ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NOT NULL,
   "IS_READ" DECIMAL(18,0) NULL
);

-- Creating table 'HU_TERMINATION_PROCESS'
CREATE TABLE "dbo"."HU_TERMINATION_PROCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "TIME_OVER" DECIMAL(18,0) NULL,
   "TIME_OVER_OTHER" DECIMAL(18,0) NULL,
   "TER_LASTDATE" DATETIME NULL,
   "REASON_DETAIL" NVARCHAR(4000) NULL,
   "IS_COMMIT" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "REASON_ID" DECIMAL(18,0) NULL,
   "IS_READ" DECIMAL(18,0) NULL,
   "NOTY_DATE" DATETIME NULL
);

-- Creating table 'PE_WORK_PROCESS'
CREATE TABLE "dbo"."PE_WORK_PROCESS" (
   "ID" DECIMAL(18,0) NOT NULL,
   "EMPLOYEE_ID" DECIMAL(18,0) NULL,
   "STATUS" DECIMAL(18,0) NULL,
   "TYPE_ID" DECIMAL(18,0) NULL,
   "CREATED_DATE" DATETIME NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "MODIFIED_DATE" DATETIME NULL,
   "MODIFIED_BY" NVARCHAR(4000) NULL,
   "MODIFIED_LOG" NVARCHAR(4000) NULL,
   "PROBLEMS" NVARCHAR(4000) NULL,
   "REQUESTS" NVARCHAR(4000) NULL,
   "MANAGER_ID" DECIMAL(18,0) NULL,
   "IS_CHANGE_SAL" DECIMAL(18,0) NULL,
   "IS_CHANGE_TITLE" DECIMAL(18,0) NULL,
   "IS_BONHIEM" DECIMAL(18,0) NULL,
   "IS_THOINHIEM" DECIMAL(18,0) NULL,
   "IS_READ" DECIMAL(18,0) NULL,
   "NOTY_DATE" DATETIME NULL,
   "NOTE" NVARCHAR(MAX) NULL
);

-- Creating table 'SE_CONFIG'
CREATE TABLE "dbo"."SE_CONFIG" (
   "ID" DECIMAL(18,0) NOT NULL,
   "CODE" NVARCHAR(4000) NULL,
   "NAME" NVARCHAR(4000) NULL,
   "VALUE" NVARCHAR(4000) NULL,
   "MODULE" INT NULL,
   "NOTE" NVARCHAR(4000) NULL
);

-- Creating table 'SE_ACTION_LOG'
CREATE TABLE "dbo"."SE_ACTION_LOG" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NULL,
   "FULLNAME" NVARCHAR(4000) NULL,
   "MOBILE" NVARCHAR(4000) NULL,
   "EMAIL" NVARCHAR(4000) NULL,
   "ACTION_NAME" NVARCHAR(4000) NULL,
   "ACTION_DATE" DATETIME NULL,
   "OBJECT_ID" DECIMAL(18,0) NULL,
   "OBJECT_NAME" NVARCHAR(4000) NULL,
   "IP" NVARCHAR(4000) NULL,
   "COMPUTER_NAME" NVARCHAR(4000) NULL,
   "VIEW_NAME" NVARCHAR(4000) NULL,
   "VIEW_DESCRIPTION" NVARCHAR(4000) NULL,
   "VIEW_GROUP" NVARCHAR(4000) NULL,
   "ACTION_TYPE" NVARCHAR(4000) NULL,
   "LOCATION" NVARCHAR(4000) NULL,
   "GROUP_NAMES" NVARCHAR(4000) NULL,
   "OBJECT_ORIGINAL" NVARCHAR(MAX) NULL,
   "OBJECT_CURRENT" NVARCHAR(MAX) NULL,
   "OBJECT_CHANGE" NVARCHAR(MAX) NULL,
   "ACTION_COMMENT" NVARCHAR(4000) NULL,
   "PLATFORM" NVARCHAR(4000) NULL
);

-- Creating table 'SE_LOG_DTL'
CREATE TABLE "dbo"."SE_LOG_DTL" (
   "ID" DECIMAL(18,0) NOT NULL,
   "COL_NAME" NVARCHAR(4000) NULL,
   "OLD_VALUE" NVARCHAR(4000) NULL,
   "NEW_VALUE" NVARCHAR(4000) NULL,
   "SE_ACTION_LOG_ID" DECIMAL(18,0) NULL
);

-- Creating table 'SE_ACTION_LOG1'
CREATE TABLE "dbo"."SE_ACTION_LOG1" (
   "ID" DECIMAL(18,0) NOT NULL,
   "USERNAME" NVARCHAR(4000) NULL,
   "FULLNAME" NVARCHAR(4000) NULL,
   "MOBILE" NVARCHAR(4000) NULL,
   "EMAIL" NVARCHAR(4000) NULL,
   "ACTION_NAME" NVARCHAR(4000) NULL,
   "ACTION_DATE" DATETIME NULL,
   "OBJECT_ID" DECIMAL(18,0) NULL,
   "OBJECT_NAME" NVARCHAR(4000) NULL,
   "IP" NVARCHAR(4000) NULL,
   "COMPUTER_NAME" NVARCHAR(4000) NULL,
   "VIEW_NAME" NVARCHAR(4000) NULL,
   "VIEW_DESCRIPTION" NVARCHAR(4000) NULL,
   "VIEW_GROUP" NVARCHAR(4000) NULL,
   "ACTION_TYPE" NVARCHAR(4000) NULL,
   "LOCATION" NVARCHAR(4000) NULL,
   "GROUP_NAMES" NVARCHAR(4000) NULL,
   "OBJECT_ORIGINAL" NVARCHAR(MAX) NULL,
   "OBJECT_CURRENT" NVARCHAR(MAX) NULL,
   "OBJECT_CHANGE" NVARCHAR(MAX) NULL,
   "ACTION_COMMENT" NVARCHAR(4000) NULL,
   "PLATFORM" NVARCHAR(4000) NULL
);

-- Creating table 'SE_NOTIFICATION'
CREATE TABLE "dbo"."SE_NOTIFICATION" (
   "ID" DECIMAL(18,0) NOT NULL,
   "NVALUE" NVARCHAR(4000) NULL,
   "SVALUE" NVARCHAR(4000) NULL,
   "MESSAGE" NVARCHAR(4000) NULL,
   "SENT_DATE" DATETIME NULL,
   "CREATED_DATE" DATETIME NULL,
   "FROM_EMPLOYEE_ID" INT NULL,
   "TO_EMPLOYEE_ID" INT NULL,
   "CREATED_BY" NVARCHAR(4000) NULL,
   "CREATED_LOG" NVARCHAR(4000) NULL,
   "SEND_LOG" NVARCHAR(4000) NULL,
   "SEND_NUMBER" DECIMAL(18,0) NULL,
   "ID_REGGROUP" DECIMAL(18,0) NULL,
   "SEND_STATUS" DECIMAL(18,0) NULL,
   "LEVEL_APPROVED" DECIMAL(18,0) NULL,
   "LEVEL_STATUS" DECIMAL(18,0) NULL,
   "ACTION_TEXT" VARCHAR(8000) NULL,
   "PROCESS_TYPE" VARCHAR(8000) NULL,
   "SEEN_DATE" DATETIME NULL
);

-- Creating table 'SE_GRP_SE_USR'
CREATE TABLE "dbo"."SE_GRP_SE_USR" (
   "SE_GROUPS_ID" DECIMAL(18,0) NOT NULL,
   "SE_USERS_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_GROUP_REPORT'
CREATE TABLE "dbo"."SE_GROUP_REPORT" (
   "SE_GROUPS_ID" DECIMAL(18,0) NOT NULL,
   "SE_REPORTS_ID" DECIMAL(18,0) NOT NULL
);

-- Creating table 'SE_USER_REPORT'
CREATE TABLE "dbo"."SE_USER_REPORT" (
   "SE_REPORT_ID" DECIMAL(18,0) NOT NULL,
   "SE_USER_ID" DECIMAL(18,0) NOT NULL
);


-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on "ID"in table 'SE_GROUP'
ALTER TABLE "dbo"."SE_GROUP"
ADD CONSTRAINT "PK_SE_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_FUNCTION'
ALTER TABLE "dbo"."SE_FUNCTION"
ADD CONSTRAINT "PK_SE_FUNCTION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER'
ALTER TABLE "dbo"."SE_USER"
ADD CONSTRAINT "PK_SE_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_MODULE'
ALTER TABLE "dbo"."SE_MODULE"
ADD CONSTRAINT "PK_SE_MODULE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_GROUP_PERMISSION'
ALTER TABLE "dbo"."SE_GROUP_PERMISSION"
ADD CONSTRAINT "PK_SE_GROUP_PERMISSION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "PK_OT_OTHER_LIST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_GROUP'
ALTER TABLE "dbo"."OT_OTHER_LIST_GROUP"
ADD CONSTRAINT "PK_OT_OTHER_LIST_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "PK_OT_OTHER_LIST_TYPE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "PK_SE_REPORT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "PK_HU_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_FUNCTION_GROUP'
ALTER TABLE "dbo"."SE_FUNCTION_GROUP"
ADD CONSTRAINT "PK_SE_FUNCTION_GROUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "PK_HU_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TERMINATE'
ALTER TABLE "dbo"."HU_TERMINATE"
ADD CONSTRAINT "PK_HU_TERMINATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_MAIL'
ALTER TABLE "dbo"."SE_MAIL"
ADD CONSTRAINT "PK_SE_MAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REMINDER'
ALTER TABLE "dbo"."SE_REMINDER"
ADD CONSTRAINT "PK_SE_REMINDER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_PROCESS'
ALTER TABLE "dbo"."SE_APP_PROCESS"
ADD CONSTRAINT "PK_SE_APP_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_SETUP'
ALTER TABLE "dbo"."SE_APP_SETUP"
ADD CONSTRAINT "PK_SE_APP_SETUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_SETUPEXT'
ALTER TABLE "dbo"."SE_APP_SETUPEXT"
ADD CONSTRAINT "PK_SE_APP_SETUPEXT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_TEMPLATE'
ALTER TABLE "dbo"."SE_APP_TEMPLATE"
ADD CONSTRAINT "PK_SE_APP_TEMPLATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_APP_TEMPLATE_DTL'
ALTER TABLE "dbo"."SE_APP_TEMPLATE_DTL"
ADD CONSTRAINT "PK_SE_APP_TEMPLATE_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORKING'
ALTER TABLE "dbo"."HU_WORKING"
ADD CONSTRAINT "PK_HU_WORKING"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ORG_ID", "USERNAME"in table 'SE_CHOSEN_ORG'
ALTER TABLE "dbo"."SE_CHOSEN_ORG"
ADD CONSTRAINT "PK_SE_CHOSEN_ORG"
   PRIMARY KEY ("ORG_ID", "USERNAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "EMPLOYEE_ID"in table 'HU_EMPLOYEE_CV'
ALTER TABLE "dbo"."HU_EMPLOYEE_CV"
ADD CONSTRAINT "PK_HU_EMPLOYEE_CV"
   PRIMARY KEY ("EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_STAFF_RANK'
ALTER TABLE "dbo"."HU_STAFF_RANK"
ADD CONSTRAINT "PK_HU_STAFF_RANK"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_LDAP'
ALTER TABLE "dbo"."SE_LDAP"
ADD CONSTRAINT "PK_SE_LDAP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_ORG_ACCESS'
ALTER TABLE "dbo"."SE_USER_ORG_ACCESS"
ADD CONSTRAINT "PK_SE_USER_ORG_ACCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_PERMISSION'
ALTER TABLE "dbo"."SE_USER_PERMISSION"
ADD CONSTRAINT "PK_SE_USER_PERMISSION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_USERS_ID", "SE_GROUPS_ID"in table 'HUV_SE_GRP_SE_USR'
ALTER TABLE "dbo"."HUV_SE_GRP_SE_USR"
ADD CONSTRAINT "PK_HUV_SE_GRP_SE_USR"
   PRIMARY KEY ("SE_USERS_ID", "SE_GROUPS_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CODE_NAME"in table 'SE_VIEW_CONFIG'
ALTER TABLE "dbo"."SE_VIEW_CONFIG"
ADD CONSTRAINT "PK_SE_VIEW_CONFIG"
   PRIMARY KEY ("CODE_NAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'AT_TIME_MANUAL'
ALTER TABLE "dbo"."AT_TIME_MANUAL"
ADD CONSTRAINT "PK_AT_TIME_MANUAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "CODE_NAME"in table 'SE_CASE_CONFIG'
ALTER TABLE "dbo"."SE_CASE_CONFIG"
ADD CONSTRAINT "PK_SE_CASE_CONFIG"
   PRIMARY KEY ("CODE_NAME" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_SIGNER'
ALTER TABLE "dbo"."HU_SIGNER"
ADD CONSTRAINT "PK_HU_SIGNER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_MAIL_TEMPLATE'
ALTER TABLE "dbo"."SE_MAIL_TEMPLATE"
ADD CONSTRAINT "PK_SE_MAIL_TEMPLATE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_NATION'
ALTER TABLE "dbo"."HU_NATION"
ADD CONSTRAINT "PK_HU_NATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_GROUP_ORG_ACCESS'
ALTER TABLE "dbo"."SE_GROUP_ORG_ACCESS"
ADD CONSTRAINT "PK_SE_GROUP_ORG_ACCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_GROUP_ORG_FUN_ACCESS'
ALTER TABLE "dbo"."SE_GROUP_ORG_FUN_ACCESS"
ADD CONSTRAINT "PK_SE_GROUP_ORG_FUN_ACCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HUV_ORGANIZATION'
ALTER TABLE "dbo"."HUV_ORGANIZATION"
ADD CONSTRAINT "PK_HUV_ORGANIZATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_WORK_PLACE'
ALTER TABLE "dbo"."HU_WORK_PLACE"
ADD CONSTRAINT "PK_HU_WORK_PLACE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_REGISTER_USER'
ALTER TABLE "dbo"."SE_REGISTER_USER"
ADD CONSTRAINT "PK_SE_REGISTER_USER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_GROUPS_ID", "SE_USERS_ID"in table 'SE_GRP_SE_USR1'
ALTER TABLE "dbo"."SE_GRP_SE_USR1"
ADD CONSTRAINT "PK_SE_GRP_SE_USR1"
   PRIMARY KEY ("SE_GROUPS_ID", "SE_USERS_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_PERMISSION_ORG'
ALTER TABLE "dbo"."SE_USER_PERMISSION_ORG"
ADD CONSTRAINT "PK_SE_USER_PERMISSION_ORG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_SYSTEM_MAINTAIN'
ALTER TABLE "dbo"."SE_SYSTEM_MAINTAIN"
ADD CONSTRAINT "PK_SE_SYSTEM_MAINTAIN"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_REQUEST'
ALTER TABLE "dbo"."TR_REQUEST"
ADD CONSTRAINT "PK_TR_REQUEST"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'TR_COURSE'
ALTER TABLE "dbo"."TR_COURSE"
ADD CONSTRAINT "PK_TR_COURSE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_BACKGROUND_PORTAL'
ALTER TABLE "dbo"."SE_BACKGROUND_PORTAL"
ADD CONSTRAINT "PK_SE_BACKGROUND_PORTAL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE_BLD'
ALTER TABLE "dbo"."HU_TITLE_BLD"
ADD CONSTRAINT "PK_HU_TITLE_BLD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_FRAME_PRODUCTIVITY'
ALTER TABLE "dbo"."PA_FRAME_PRODUCTIVITY"
ADD CONSTRAINT "PK_PA_FRAME_PRODUCTIVITY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PA_FRAME_SALARY'
ALTER TABLE "dbo"."PA_FRAME_SALARY"
ADD CONSTRAINT "PK_PA_FRAME_SALARY"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_ORGANIZATION_OM'
ALTER TABLE "dbo"."HU_ORGANIZATION_OM"
ADD CONSTRAINT "PK_HU_ORGANIZATION_OM"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_WORK_EMPLOYEE'
ALTER TABLE "dbo"."PE_WORK_EMPLOYEE"
ADD CONSTRAINT "PK_PE_WORK_EMPLOYEE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_WORK_MANAGER'
ALTER TABLE "dbo"."PE_WORK_MANAGER"
ADD CONSTRAINT "PK_PE_WORK_MANAGER"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_WORK_MANAGER_CONCLUDE'
ALTER TABLE "dbo"."PE_WORK_MANAGER_CONCLUDE"
ADD CONSTRAINT "PK_PE_WORK_MANAGER_CONCLUDE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_JOB_BAND'
ALTER TABLE "dbo"."HU_JOB_BAND"
ADD CONSTRAINT "PK_HU_JOB_BAND"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HUV_ORGANIZATION_CHILD'
ALTER TABLE "dbo"."HUV_ORGANIZATION_CHILD"
ADD CONSTRAINT "PK_HUV_ORGANIZATION_CHILD"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PROCESS_APPROVED_STATUS'
ALTER TABLE "dbo"."PROCESS_APPROVED_STATUS"
ADD CONSTRAINT "PK_PROCESS_APPROVED_STATUS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TITLE'
ALTER TABLE "dbo"."HU_TITLE"
ADD CONSTRAINT "PK_HU_TITLE"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_SIGNER_SETUP'
ALTER TABLE "dbo"."HU_SIGNER_SETUP"
ADD CONSTRAINT "PK_HU_SIGNER_SETUP"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_FOLDERS'
ALTER TABLE "dbo"."HU_FOLDERS"
ADD CONSTRAINT "PK_HU_FOLDERS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_PERMISSION_ORG_DETAIL'
ALTER TABLE "dbo"."SE_USER_PERMISSION_ORG_DETAIL"
ADD CONSTRAINT "PK_SE_USER_PERMISSION_ORG_DETAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_USER_PERMISSION_ORG_WL'
ALTER TABLE "dbo"."SE_USER_PERMISSION_ORG_WL"
ADD CONSTRAINT "PK_SE_USER_PERMISSION_ORG_WL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PO_EVENT_SEND_MAIL'
ALTER TABLE "dbo"."PO_EVENT_SEND_MAIL"
ADD CONSTRAINT "PK_PO_EVENT_SEND_MAIL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PO_EVENT'
ALTER TABLE "dbo"."PO_EVENT"
ADD CONSTRAINT "PK_PO_EVENT"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "PO_EVENT_ID", "EMPLOYEE_ID"in table 'PO_EVENT_EMP'
ALTER TABLE "dbo"."PO_EVENT_EMP"
ADD CONSTRAINT "PK_PO_EVENT_EMP"
   PRIMARY KEY ("PO_EVENT_ID", "EMPLOYEE_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'HU_TERMINATION_PROCESS'
ALTER TABLE "dbo"."HU_TERMINATION_PROCESS"
ADD CONSTRAINT "PK_HU_TERMINATION_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'PE_WORK_PROCESS'
ALTER TABLE "dbo"."PE_WORK_PROCESS"
ADD CONSTRAINT "PK_PE_WORK_PROCESS"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_CONFIG'
ALTER TABLE "dbo"."SE_CONFIG"
ADD CONSTRAINT "PK_SE_CONFIG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_ACTION_LOG'
ALTER TABLE "dbo"."SE_ACTION_LOG"
ADD CONSTRAINT "PK_SE_ACTION_LOG"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_LOG_DTL'
ALTER TABLE "dbo"."SE_LOG_DTL"
ADD CONSTRAINT "PK_SE_LOG_DTL"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_ACTION_LOG1'
ALTER TABLE "dbo"."SE_ACTION_LOG1"
ADD CONSTRAINT "PK_SE_ACTION_LOG1"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "ID"in table 'SE_NOTIFICATION'
ALTER TABLE "dbo"."SE_NOTIFICATION"
ADD CONSTRAINT "PK_SE_NOTIFICATION"
   PRIMARY KEY ("ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_GROUPS_ID", "SE_USERS_ID"in table 'SE_GRP_SE_USR'
ALTER TABLE "dbo"."SE_GRP_SE_USR"
ADD CONSTRAINT "PK_SE_GRP_SE_USR"
   PRIMARY KEY ("SE_GROUPS_ID", "SE_USERS_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_GROUPS_ID", "SE_REPORTS_ID"in table 'SE_GROUP_REPORT'
ALTER TABLE "dbo"."SE_GROUP_REPORT"
ADD CONSTRAINT "PK_SE_GROUP_REPORT"
   PRIMARY KEY ("SE_GROUPS_ID", "SE_REPORTS_ID" )
   ENABLE
   VALIDATE;


-- Creating primary key on "SE_REPORT_ID", "SE_USER_ID"in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "PK_SE_USER_REPORT"
   PRIMARY KEY ("SE_REPORT_ID", "SE_USER_ID" )
   ENABLE
   VALIDATE;


-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on "SE_GROUPS_ID" in table 'SE_GRP_SE_USR'
ALTER TABLE "dbo"."SE_GRP_SE_USR"
ADD CONSTRAINT "FK_SE_GRP_SE_USR_SE_GROUP"
   FOREIGN KEY ("SE_GROUPS_ID")
   REFERENCES "dbo"."SE_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_GRP_SE_USR_SE_GROUP'
CREATE INDEX "IX_FK_SE_GRP_SE_USR_SE_GROUP"
ON "dbo"."SE_GRP_SE_USR"
   ("SE_GROUPS_ID");

-- Creating foreign key on "SE_USERS_ID" in table 'SE_GRP_SE_USR'
ALTER TABLE "dbo"."SE_GRP_SE_USR"
ADD CONSTRAINT "FK_SE_GRP_SE_USR_SE_USER"
   FOREIGN KEY ("SE_USERS_ID")
   REFERENCES "dbo"."SE_USER"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_GRP_SE_USR_SE_USER'
CREATE INDEX "IX_FK_SE_GRP_SE_USR_SE_USER"
ON "dbo"."SE_GRP_SE_USR"
   ("SE_USERS_ID");

-- Creating foreign key on "MODULE_ID" in table 'SE_FUNCTION'
ALTER TABLE "dbo"."SE_FUNCTION"
ADD CONSTRAINT "FK_SM_SF"
   FOREIGN KEY ("MODULE_ID")
   REFERENCES "dbo"."SE_MODULE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SM_SF'
CREATE INDEX "IX_FK_SM_SF"
ON "dbo"."SE_FUNCTION"
   ("MODULE_ID");

-- Creating foreign key on "FUNCTION_ID" in table 'SE_GROUP_PERMISSION'
ALTER TABLE "dbo"."SE_GROUP_PERMISSION"
ADD CONSTRAINT "FK_SF_SGP"
   FOREIGN KEY ("FUNCTION_ID")
   REFERENCES "dbo"."SE_FUNCTION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SF_SGP'
CREATE INDEX "IX_FK_SF_SGP"
ON "dbo"."SE_GROUP_PERMISSION"
   ("FUNCTION_ID");

-- Creating foreign key on "GROUP_ID" in table 'SE_GROUP_PERMISSION'
ALTER TABLE "dbo"."SE_GROUP_PERMISSION"
ADD CONSTRAINT "FK_SG_SGP"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."SE_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SG_SGP'
CREATE INDEX "IX_FK_SG_SGP"
ON "dbo"."SE_GROUP_PERMISSION"
   ("GROUP_ID");

-- Creating foreign key on "GROUP_ID" in table 'OT_OTHER_LIST_TYPE'
ALTER TABLE "dbo"."OT_OTHER_LIST_TYPE"
ADD CONSTRAINT "FK_OOLG_OOLT"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLG_OOLT'
CREATE INDEX "IX_FK_OOLG_OOLT"
ON "dbo"."OT_OTHER_LIST_TYPE"
   ("GROUP_ID");

-- Creating foreign key on "TYPE_ID" in table 'OT_OTHER_LIST'
ALTER TABLE "dbo"."OT_OTHER_LIST"
ADD CONSTRAINT "FK_OOLT_OOL"
   FOREIGN KEY ("TYPE_ID")
   REFERENCES "dbo"."OT_OTHER_LIST_TYPE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_OOLT_OOL'
CREATE INDEX "IX_FK_OOLT_OOL"
ON "dbo"."OT_OTHER_LIST"
   ("TYPE_ID");

-- Creating foreign key on "MODULE_ID" in table 'SE_REPORT'
ALTER TABLE "dbo"."SE_REPORT"
ADD CONSTRAINT "FK_SM_SR"
   FOREIGN KEY ("MODULE_ID")
   REFERENCES "dbo"."SE_MODULE"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SM_SR'
CREATE INDEX "IX_FK_SM_SR"
ON "dbo"."SE_REPORT"
   ("MODULE_ID");

-- Creating foreign key on "SE_GROUPS_ID" in table 'SE_GROUP_REPORT'
ALTER TABLE "dbo"."SE_GROUP_REPORT"
ADD CONSTRAINT "FK_SE_GROUP_REPORT_SE_GROUP"
   FOREIGN KEY ("SE_GROUPS_ID")
   REFERENCES "dbo"."SE_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_GROUP_REPORT_SE_GROUP'
CREATE INDEX "IX_FK_SE_GROUP_REPORT_SE_GROUP"
ON "dbo"."SE_GROUP_REPORT"
   ("SE_GROUPS_ID");

-- Creating foreign key on "SE_REPORTS_ID" in table 'SE_GROUP_REPORT'
ALTER TABLE "dbo"."SE_GROUP_REPORT"
ADD CONSTRAINT "FK_SE_GROUP_REPORT_SE_REPORT"
   FOREIGN KEY ("SE_REPORTS_ID")
   REFERENCES "dbo"."SE_REPORT"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_GROUP_REPORT_SE_REPORT'
CREATE INDEX "IX_FK_SE_GROUP_REPORT_SE_REPORT"
ON "dbo"."SE_GROUP_REPORT"
   ("SE_REPORTS_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION'
ALTER TABLE "dbo"."HU_ORGANIZATION"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG"
ON "dbo"."HU_ORGANIZATION"
   ("PARENT_ID");

-- Creating foreign key on "GROUP_ID" in table 'SE_FUNCTION'
ALTER TABLE "dbo"."SE_FUNCTION"
ADD CONSTRAINT "FK_SFG_SF"
   FOREIGN KEY ("GROUP_ID")
   REFERENCES "dbo"."SE_FUNCTION_GROUP"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SFG_SF'
CREATE INDEX "IX_FK_SFG_SF"
ON "dbo"."SE_FUNCTION"
   ("GROUP_ID");

-- Creating foreign key on "ORG_ID" in table 'HU_EMPLOYEE'
ALTER TABLE "dbo"."HU_EMPLOYEE"
ADD CONSTRAINT "FK_HU_ORG_HU_EMP"
   FOREIGN KEY ("ORG_ID")
   REFERENCES "dbo"."HU_ORGANIZATION"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_EMP'
CREATE INDEX "IX_FK_HU_ORG_HU_EMP"
ON "dbo"."HU_EMPLOYEE"
   ("ORG_ID");

-- Creating foreign key on "SE_REPORT_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_REPORT"
   FOREIGN KEY ("SE_REPORT_ID")
   REFERENCES "dbo"."SE_REPORT"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_REPORT'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_REPORT"
ON "dbo"."SE_USER_REPORT"
   ("SE_REPORT_ID");

-- Creating foreign key on "SE_USER_ID" in table 'SE_USER_REPORT'
ALTER TABLE "dbo"."SE_USER_REPORT"
ADD CONSTRAINT "FK_SE_USER_REPORT_SE_USER"
   FOREIGN KEY ("SE_USER_ID")
   REFERENCES "dbo"."SE_USER"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_USER_REPORT_SE_USER'
CREATE INDEX "IX_FK_SE_USER_REPORT_SE_USER"
ON "dbo"."SE_USER_REPORT"
   ("SE_USER_ID");

-- Creating foreign key on "PARENT_ID" in table 'HU_ORGANIZATION_OM'
ALTER TABLE "dbo"."HU_ORGANIZATION_OM"
ADD CONSTRAINT "FK_HU_ORG_HU_ORG_OM"
   FOREIGN KEY ("PARENT_ID")
   REFERENCES "dbo"."HU_ORGANIZATION_OM"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_HU_ORG_HU_ORG_OM'
CREATE INDEX "IX_FK_HU_ORG_HU_ORG_OM"
ON "dbo"."HU_ORGANIZATION_OM"
   ("PARENT_ID");

-- Creating foreign key on "SE_ACTION_LOG_ID" in table 'SE_LOG_DTL'
ALTER TABLE "dbo"."SE_LOG_DTL"
ADD CONSTRAINT "FK_SE_LOG_ACTION"
   FOREIGN KEY ("SE_ACTION_LOG_ID")
   REFERENCES "dbo"."SE_ACTION_LOG"
       ("ID")
   ENABLE
   VALIDATE;

-- Creating index for FOREIGN KEY 'FK_SE_LOG_ACTION'
CREATE INDEX "IX_FK_SE_LOG_ACTION"
ON "dbo"."SE_LOG_DTL"
   ("SE_ACTION_LOG_ID");

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------
