'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ctrlSignWorkEdit

    '''<summary>
    '''ctrlMessageBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctrlMessageBox As Global.Common.ctrlMessageBox

    '''<summary>
    '''RadSplitter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadSplitter1 As Global.Telerik.Web.UI.RadSplitter

    '''<summary>
    '''RadPane5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadPane5 As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''tbarMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbarMain As Global.Telerik.Web.UI.RadToolBar

    '''<summary>
    '''LeftPane control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeftPane As Global.Telerik.Web.UI.RadPane

    '''<summary>
    '''txtEmployeeCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeCode As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtOrgName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrgName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmployeeName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''txtTitleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitleName As Global.Telerik.Web.UI.RadTextBox

    '''<summary>
    '''lbPeroidName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPeroidName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEndDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode1 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr2 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode2 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr3 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode3 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr4 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode4 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr5 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode5 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr6 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode6 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr7 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode7 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr8 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode8 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr9 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode9 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr10 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode10 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr11 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode11 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr12 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode12 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr13 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit13 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode13 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr14 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode14 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr15 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit15 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode15 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr16 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit16 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode16 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr17 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit17 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode17 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr18 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit18 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode18 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr19 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit19 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode19 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr20 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit20 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode20 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr21 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit21 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode21 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr22 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit22 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode22 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr23 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit23 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode23 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr24 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit24 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode24 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr25 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit25 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode25 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr26 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit26 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode26 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr27 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit27 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode27 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr28 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit28 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode28 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr29 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit29 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode29 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr30 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit30 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode30 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''tr31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr31 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbSTT31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSTT31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDay31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDay31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbCode31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCode31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbDayEdit31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDayEdit31 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cboCode31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCode31 As Global.Telerik.Web.UI.RadComboBox

    '''<summary>
    '''RadCodeBlock1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCodeBlock1 As Global.Telerik.Web.UI.RadCodeBlock
End Class
