Public Class StocksDTO
    Public Property ID As Decimal
    Public Property EMPLOYEE_ID As Decimal?
    Public Property CODE As String
    Public Property EMPLOYEE_STOCK_CODE As String
    Public Property EMPLOYEE_CODE As String
    Public Property EMPLOYEE_NAME As String
    Public Property ORG_ID As Decimal?
    Public Property ORG_NAME As String
    Public Property ORG_DESC As String
    Public Property ORG_CODE As String
    Public Property LOCATION_ID As Decimal?
    Public Property LOCATION_NAME As String
    Public Property TITLE_ID As Decimal?
    Public Property TITLE_NAME As String
    Public Property STATE_DATE As Date?
    Public Property EFFECTED_DATE As Date?
    Public Property STOCKS_TYPE As Decimal?
    Public Property STOCKS_TYPE_NAME As String
    Public Property PAY_TYPE As Decimal?
    Public Property PAY_TYPE_NAME As String
    Public Property STOCK_DEAL As Decimal?
    Public Property MONEY_DEAL As Decimal?
    Public Property PERCENT As Decimal?
    Public Property MONTH As Decimal?
    Public Property TIME As Decimal?
    Public Property NOTE As String
    Public Property FILE_NAME As String
    Public Property UPLOAD_FILE_NAME As String
    Public Property CREATED_DATE As Date?
    Public Property CREATED_BY As String
    Public Property CREATED_LOG As String
    Public Property MODIFIED_DATE As Date?
    Public Property MODIFIED_BY As String
    Public Property MODIFIED_LOG As String
End Class
