Function: GetOrganization
Datetime: 08/03/2022 10:51:12 AM
Error message: An error occurred while reading from the store provider's data reader. See the inner exception for details.
Stack trace:    at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrganization(String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 3112
Inner error message: ORA-30004: when using SYS_CONNECT_BY_PATH function, cannot have separator as part of column value
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleDataReader.Read()
   at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
Other Text: iProfile

Function: GetOrganization
Datetime: 08/03/2022 10:53:14 AM
Error message: An error occurred while reading from the store provider's data reader. See the inner exception for details.
Stack trace:    at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrganization(String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 3112
Inner error message: ORA-30004: when using SYS_CONNECT_BY_PATH function, cannot have separator as part of column value
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleDataReader.Read()
   at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
Other Text: iProfile

Function: GetOrganization
Datetime: 08/03/2022 10:55:35 AM
Error message: An error occurred while reading from the store provider's data reader. See the inner exception for details.
Stack trace:    at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
   at System.Data.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrganization(String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 3112
Inner error message: ORA-30004: when using SYS_CONNECT_BY_PATH function, cannot have separator as part of column value
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleDataReader.Read()
   at System.Data.Common.Internal.Materialization.Shaper`1.StoreRead()
Other Text: iProfile

