Function: GetWorkingAllowance1
Datetime: 07/26/2022 9:52:27 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 9:52:30 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 9:53:49 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 9:57:16 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 9:57:57 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:00:19 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:02:43 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:03:06 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:03:20 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:04:09 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:05:50 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/26/2022 10:07:07 AM
Error message: Conversion from type 'DBNull' to type 'String' is not valid.
Stack trace:    at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 493
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 12:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:22 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/26/2022 1:04:23 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

