Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:24:29 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5856
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:25:02 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5856
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:25:17 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\da3ee024-6e39-4857-b494-beb8fa380b93\33.png'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5871
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:43:46 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5858
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:50:20 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\a6e1355d-855d-4c65-9be4-ce5b42f4f398\Import_NhanVien20220627082940.xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5873
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:50:46 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\a6e1355d-855d-4c65-9be4-ce5b42f4f398\Import_NhanVien20220627082940.xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5873
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:52:15 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\a6e1355d-855d-4c65-9be4-ce5b42f4f398\Import_NhanVien20220627082940.xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5873
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:53:30 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\f06f454c-7f47-4d79-8561-90f59db95420\Import_phucap20220624 (1).xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5873
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 06/28/2022 9:55:05 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffWorkingBefore\f06f454c-7f47-4d79-8561-90f59db95420\Import_phucap20220624 (1).xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5873
Other Text: iProfile

Function: InsertEmployee
Datetime: 06/28/2022 10:07:46 AM
Error message: An error occurred while updating the entries. See the inner exception for details.
Stack trace:    at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
   at System.Data.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at ProfileDAL.ProfileContext.SaveChanges(UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileContext.vb:line 56
   at ProfileDAL.ProfileRepository.InsertEmployee(EmployeeDTO objEmp, UserLog log, Decimal& gID, String& _strEmpCode, Byte[] _imageBinary, EmployeeCVDTO objEmpCV, EmployeeEduDTO objEmpEdu, EmployeeHealthDTO objEmpHealth) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 1655
Inner error message: ORA-02291: integrity constraint (BCG_DEV.FK_HUEMD_HUEM) violated - parent key not found
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Mapping.Update.Internal.DynamicUpdateCommand.Execute(UpdateTranslator translator, EntityConnection connection, Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
Other Text: iProfile

Function: InsertEmployee
Datetime: 06/28/2022 10:11:47 AM
Error message: An error occurred while updating the entries. See the inner exception for details.
Stack trace:    at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
   at System.Data.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at ProfileDAL.ProfileContext.SaveChanges(UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileContext.vb:line 56
   at ProfileDAL.ProfileRepository.InsertEmployee(EmployeeDTO objEmp, UserLog log, Decimal& gID, String& _strEmpCode, Byte[] _imageBinary, EmployeeCVDTO objEmpCV, EmployeeEduDTO objEmpEdu, EmployeeHealthDTO objEmpHealth) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 1655
Inner error message: ORA-02291: integrity constraint (BCG_DEV.FK_HUEMD_HUEM) violated - parent key not found
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Mapping.Update.Internal.DynamicUpdateCommand.Execute(UpdateTranslator translator, EntityConnection connection, Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:09 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:09 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:10 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:10 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:10 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 1:01:10 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:23:36 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:23:39 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:23:46 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:23:52 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:27:10 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:27:22 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:28:37 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:28:41 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:32:00 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: GetOrgTreeList
Datetime: 06/28/2022 2:32:04 PM
Error message: Value cannot be null.
Parameter name: source
Stack trace:    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.GetOrgTreeList(String username, String sACT) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.List.vb:line 8950
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:55 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:55 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:55 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:55 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:56 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 06/28/2022 4:05:56 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2037
Other Text: iProfile

