Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:36:05 AM
Error message: Could not find a part of the path 'D:\GIT\BCG_DEV_NEW\HistaffServiceHost\Profile\UploadFile\StaffFamily\2f1145d4-e758-40d6-a22d-b9cf18c5771a\WaveImport.xls'.
Stack trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5891
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:40:13 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:41:23 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:41:41 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:42:35 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 9:44:11 AM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 12:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:24 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:24 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:25 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:26 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:26 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: ApproveContract_Background
Datetime: 07/01/2022 1:56:26 PM
Error message: Non-static method requires a target.
Stack trace:    at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryGetFieldOrPropertyValue(MemberExpression me, Object instance, Object& memberValue)
   at System.Data.Objects.ELinq.QueryParameterExpression.TryEvaluatePath(Expression expression, ConstantExpression& constantExpression)
   at System.Data.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)
   at System.Data.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.ApproveContract_Background(ContractDTO objContract) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2050
Other Text: iProfile

Function: GetOtherList
Datetime: 07/01/2022 3:28:00 PM
Error message: ORA-12543: TNS:destination host unreachable
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 3:58:15 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

Function: GetFileByte_Userfile
Datetime: 07/01/2022 3:58:31 PM
Error message: Object reference not set to an instance of an object.
Stack trace:    at ProfileDAL.ProfileRepository.GetFileByte_Userfile(String fileUpload) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Employee.vb:line 5876
Other Text: iProfile

