Function: GetWorkingAllowance1
Datetime: 07/13/2022 9:58:22 AM
Error message: Column 'FILE_NAME' does not belong to table Table.
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 489
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/13/2022 9:58:23 AM
Error message: Column 'FILE_NAME' does not belong to table Table.
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 489
Other Text: iProfile

Function: GetWorkingAllowance1
Datetime: 07/13/2022 10:00:31 AM
Error message: Column 'FILE_NAME' does not belong to table Table.
Stack trace:    at System.Data.DataRow.GetDataColumn(String columnName)
   at System.Data.DataRow.get_Item(String columnName)
   at ProfileDAL.ProfileRepository.GetWorkingAllowance1(HUAllowanceDTO _filter, ParamDTO _param, Int32 PageIndex, Int32 PageSize, Int32& Total, String Sorts, UserLog log) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Working.vb:line 489
Other Text: iProfile

Function: GetOtherList
Datetime: 07/13/2022 3:04:13 PM
Error message: ORA-03135: connection lost contact
Process ID: 1584
Session ID: 590 Serial number: 40728
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: CheckEmployee_Exits
Datetime: 07/13/2022 5:19:02 PM
Error message: Sequence contains more than one element
Stack trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.CheckEmployee_Exits(String empCode) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2528
Other Text: iProfile

Function: CheckEmployee_Exits
Datetime: 07/13/2022 5:19:42 PM
Error message: Sequence contains more than one element
Stack trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.CheckEmployee_Exits(String empCode) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2528
Other Text: iProfile

Function: CheckEmployee_Exits
Datetime: 07/13/2022 5:20:56 PM
Error message: Sequence contains more than one element
Stack trace:    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at ProfileDAL.ProfileRepository.CheckEmployee_Exits(String empCode) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.Contract.vb:line 2528
Other Text: iProfile

