Function: GetOtherList
Datetime: 07/27/2022 8:57:56 PM
Error message: ORA-12170: TNS:Connect timeout occurred
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in D:\GIT\BCG_DEV_NEW\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in D:\GIT\BCG_DEV_NEW\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

