Function: GetOtherList
Datetime: 4/28/2023 3:31:14 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 3:37:22 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 4:00:19 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 4:28:51 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 5:04:19 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 5:11:02 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

Function: GetOtherList
Datetime: 4/28/2023 5:13:34 PM
Error message: 'Initial Catalog' is an invalid connection string attribute
Stack trace:    at Framework.Data.DataAccess.QueryData.ExecuteStore[T](String sql, T& obj, Boolean isDataTable) in E:\Source\BCG_DEV\Framework.Data\DataAccess\Query.vb:line 303
   at ProfileDAL.ProfileRepository.GetOtherList(String sType, String sLang, Boolean isBlank) in E:\Source\BCG_DEV\ProfileDAL\ProfileRepository.vb:line 55
Other Text: iProfile

