Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:19:10 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:23:14 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:26:04 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:28:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:28:35 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:30:32 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:30:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:32:01 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:32:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:33:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:34:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:35:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:36:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:37:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:38:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:39:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:40:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:41:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:42:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:43:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:44:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:45:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:46:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:47:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:48:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:49:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:50:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:51:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:52:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:53:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:54:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:55:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:56:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 3:57:34 PM
Error message: The specified store provider cannot be found in the configuration, or is not valid.
Stack trace:    at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Unable to find the requested .Net Framework Data Provider.  It may not be installed.
Inner stack trace:    at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:07:52 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:08:45 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:09:45 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:10:45 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:13:28 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:15:22 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:25:01 PM
Error message: Could not load file or assembly 'Oracle.DataAccess, Version=4.121.1.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack trace:    at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.EntityClient.EntityConnection.GetFactory(String providerString)
   at System.Data.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Objects.ObjectContext.CreateEntityConnection(String connectionString)
   at System.Data.Objects.ObjectContext..ctor(String connectionString, String defaultContainerName)
   at PayrollDAL.PayrollContext..ctor() in E:\Source\BCG_DEV\PayrollDAL\PayrollContext.Designer.vb:line 54
   at PayrollDAL.PayrollRepositoryBase.get_Context() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepositoryBase.vb:line 10
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:26:57 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:27:58 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:28:57 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:29:57 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:33:11 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:34:14 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:39:15 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:42:32 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:42:37 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 4:46:16 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: ORA-12638: Credential retrieval failed
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

Function: CheckAndSendPayslip
Datetime: 4/27/2023 11:58:13 PM
Error message: The underlying provider failed on Open.
Stack trace:    at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at PayrollDAL.PayrollRepository.CheckAndSendPayslip() in E:\Source\BCG_DEV\PayrollDAL\PayrollRepository.vb:line 387
Inner error message: Connection request timed out
Inner stack trace:    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck, Int32 isRecoverable, OracleLogicalTransaction m_OracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src, OracleLogicalTransaction m_oracleLogicalTransaction)
   at Oracle.DataAccess.Client.OracleConnectionOCP.Open(OracleConnection con)
   at Oracle.DataAccess.Client.OracleConnection.Open()
   at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
Other Text: iPayroll

